src/components/cv-tooltip/cv-definition-tooltip.vue, src/components/cv-tooltip/cv-interactive-tooltip.vue, src/components/cv-tooltip/cv-tooltip-notes.md, src/components/cv-tooltip/cv-tooltip-story.js, src/components/cv-tooltip/cv-tooltip.vue, src/mixins/uid-mixin.js
**New**
Added tooltip components
cv-tooltip
cv-definition-tooltip
cv-interactive-tooltip
Added mixin
uid-mixin
=> feat(cv-tooltip): add cv-tooltip components

src/components/cv-modal/cv-modal-notes.md, src/components/cv-modal/cv-modal-story.js, src/components/cv-modal/cv-modal.vue, src/components/cv-tile/cv-tile.vue, src/index.js
**Changed**
- Minor changes preferring includes to indexOf, default fixes and story names.
=> fix(minor): tidy up some code

src/components/cv-pagination/cv-pagination-notes.md, src/components/cv-pagination/cv-pagination-story.js, src/components/cv-pagination/cv-pagination.vue, src/components/cv-select/cv-select.vue
**New**
- Add pagination component
=>  feat(componnet): add pagination

src/components/cv-progress/cv-progress-story.js
**Changed**
- Correct progress story
=> fix(component): correct pagination story

package.json
**Changed**
- Allowed side effects as carbon styles were not otherwise loaded.
=> fix(package): enable side effects to load carbon scss

package.json, src/components/cv-date-picker/cv-date-picker-notes.md, src/components/cv-date-picker/cv-date-picker-story.js, src/components/cv-date-picker/cv-date-picker.vue
**New**
- Add date picker component
=> feat(component): add cv-date-pickr

src/components/cv-date-picker/cv-date-picker-story.js, src/components/cv-date-picker/cv-date-picker.vue, src/components/cv-number-input/cv-number-input-story.js, src/components/cv-number-input/cv-number-input.vue, src/components/cv-search/cv-search-story.js, src/components/cv-search/cv-search.vue, src/components/cv-select/cv-select-story.js, src/components/cv-select/cv-select.vue, src/components/cv-slider/cv-slider-story.js, src/components/cv-slider/cv-slider.vue, src/components/cv-text-area/cv-text-area-story.js, src/components/cv-text-area/cv-text-area.vue, src/components/cv-text-input/cv-text-input-story.js, src/components/cv-text-input/cv-text-input.vue, src/mixins/theme-mixin.js
Add light theme to components which support it.
**Changed**
- Components supporting the light theme
=> feat(theme): add light theme to components

src/components/cv-date-picker/cv-date-picker.vue, src/components/cv-select/cv-select.vue, src/components/cv-time-picker/cv-time-picker-notes.md, src/components/cv-time-picker/cv-time-picker-story.js, src/components/cv-time-picker/cv-time-picker.vue, src/views/sv-template-view/sv-template-view.vue
Closes #48 
Added time picker component, first pass.
**New**
time picker 
**Changed**
the select component should really be inline-flex, raise carbon issue?
=>  feat(component): attempt time picker

src/components/cv-radio-button/cv-radio-button.vue, src/components/cv-structured-list/cv-structured-list-item-selectable.vue, src/mixins/check-mixin.js
**Changed**
Case of methods onchange to onChange
=> chore(consistency): update method names to camel case

README.md
=> chore: v0.1 prep

README.md
=> chore: version 01 fixes

README.md
=> fix: circle ci pretty check

src/components/cv-accordion/cv-accordion-item.vue, src/components/cv-breadcrumb/cv-breadcrumb-item.vue, src/components/cv-date-picker/cv-date-picker.vue, src/components/cv-dropdown/cv-dropdown.vue, src/components/cv-number-input/cv-number-input.vue, src/components/cv-radio-button/cv-radio-group.vue
Add some cv-classes and move some to outside element.
=> fix: correct more cv-classes

src/components/cv-pagination/cv-pagination.vue, src/components/cv-select/cv-select-story.js, src/components/cv-select/cv-select.vue, src/components/cv-time-picker/cv-time-picker.vue
Rework select to use value and v-model as per standard vue select wrapping.
=>  chore: simplify select to match standard vue pattern 

README.md, src/components/cv-time-picker/cv-time-picker-notes.md, src/components/cv-time-picker/cv-time-picker-story.js, src/components/cv-time-picker/cv-time-picker.vue, src/utils/storybook-knobs-helper.js
Part of #80 
Demonstration of .sync pattern instead of v-model
=> chore: try dot sync pattern

src/components/cv-accordion/cv-accordion-item.vue, src/components/cv-accordion/cv-accordion.vue
src/components/cv-accordion/*.vue
=> chore: remove core carbon code from accorion

src/components/cv-dropdown/cv-dropdown.vue, src/components/cv-file-uploader/cv-file-uploader.vue, src/components/cv-radio-button/cv-radio-button-story.js, src/components/cv-radio-button/cv-radio-button.vue, src/components/cv-radio-button/cv-radio-group.vue
Improve v-model example for radio button, plus a bit of a tidy.
=> chore: tidy radio v-model, fileuploader and dropdown

package.json
Add publishConfig for package publishing.
**New**
**Changed**
- `package.json`
**Removed**
=> chore(package): update publishConfig for package publishing

src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-inline-notification/cv-inline-notification-notes.md, src/components/cv-inline-notification/cv-inline-notification-story.js, src/components/cv-inline-notification/cv-inline-notification.vue, src/components/cv-toast-notification/cv-toast-notification-notes.md, src/components/cv-toast-notification/cv-toast-notification-story.js, src/components/cv-toast-notification/cv-toast-notification.vue, src/mixins/notification-mixin.js
Removed notification component dependence on vanilla javascript.
=> chore: make notification components native vue components

src/components/cv-tile/_cv-tile-clickable.vue, src/components/cv-tile/_cv-tile-expandable.vue, src/components/cv-tile/cv-tile-story.js
Closes #108
Fixes issue with expandable tile and makes it native Vue at the same time
=> fix: fix expandable tile and make it native vue

README.md, src/components/cv-search/cv-search-story.js, src/components/cv-search/cv-search.vue, src/public/demo.html
=> chore: make search native vue

src/components/cv-modal/cv-modal-story.js, src/components/cv-overflow-menu/cv-overflow-menu.vue, src/components/cv-tooltip/cv-interactive-tooltip.vue, src/components/cv-tooltip/cv-tooltip-story.js
=> feat: make tooltip native Vue

src/components/cv-date-picker/cv-date-picker-story.js, src/components/cv-file-uploader/cv-file-uploader.vue, src/components/cv-tabs/cv-tabs-story.js, src/components/cv-tile/_cv-tile-clickable.vue, src/components/cv-tile/_cv-tile-selectable.vue, src/mixins/notification-mixin.js
Remove some unused code and correct CvTab story.
=> chore: Remove some unused code and correct CvTab story.

README.md, src/components/cv-radio-button/cv-radio-button-notes.md, src/components/cv-radio-button/cv-radio-button.vue, src/components/cv-radio-button/cv-radio-group.vue, src/components/cv-structured-list/cv-structured-list-item-selectable.vue, src/components/cv-structured-list/cv-structured-list-notes.md, src/components/cv-structured-list/cv-structured-list-story.js, src/components/cv-structured-list/cv-structured-list.vue, src/mixins/radio-mixin.js
=> feat: native Vue structured list

src/components/cv-radio-button/cv-radio-button.vue, src/components/cv-structured-list/_cv-structured-list-item-selectable.vue, src/components/cv-structured-list/_cv-structured-list-item-standard.vue, src/components/cv-structured-list/cv-structured-list-item.vue, src/components/cv-structured-list/cv-structured-list-notes.md, src/components/cv-structured-list/cv-structured-list-story.js
Reduce to a single selectable item component.
=> chore: make structured list simpler

src/components/cv-pagination/cv-pagination.vue
=> fix: issue 125

src/components/cv-dropdown/cv-dropdown-item.vue, src/components/cv-modal/cv-modal.vue, vue.config.js
=> fix: modal tab out and code tidy

src/components/cv-modal/cv-modal.vue
=> fix: modal dialog closed on self click

README.md, package.json
**New**
- CvGauge
- CvPieChart
**Changed**
- CvLink - adds router-link version
=> chore: v0_2_9

README.md
Closes #
**New**
**Changed**
**Removed**
=> fix: fix prettier

src/components/cv-content-switcher/cv-content-switcher-button.vue, src/components/cv-content-switcher/cv-content-switcher.vue
Part of #64
Changes the content-switcher use events to communicate between content-switcher-button and content-switcher.
**Changed**
- cv-content-switcher
=>  chore: remove register n deregister from content switcher

src/components/cv-tabs/cv-tab.vue, src/components/cv-tabs/cv-tabs.vue
Part of #64 
Use events for tab parent relationship.
**Changed**
- CvTabs
- CvTab
=> chore: Use events for tab parent relationship

src/components/cv-content-switcher/cv-content-switcher.vue, src/components/cv-dropdown/cv-dropdown-item.vue, src/components/cv-dropdown/cv-dropdown.vue
Part of #64 
Have $children usage check child type
**Changed**
- CvContentSwitcher
- CvDropdown
=> chore: more cautions $children use

src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-overflow-menu/cv-overflow-menu-item.vue, src/components/cv-overflow-menu/cv-overflow-menu-story.js, src/components/cv-overflow-menu/cv-overflow-menu.vue, src/components/cv-tabs/cv-tab.vue, src/components/cv-tabs/cv-tabs.vue, src/components/cv-tooltip/cv-interactive-tooltip.vue, src/components/cv-tooltip/cv-tooltip-story.js
Part of #64
Updates the parent relationship for overflow-menu and tabs.
Corrects position for overflow menu and interactive tooltip during scroll/resize.
**Changed**
- CvInteractiveTooltip
- CvOverflowMenu
- CvTabs
=> More parenting

README.md, package.json, src/components/cv-tabs/cv-tabs.vue
- Initial data-viz/bar-graph added
- Story corrections
- Change use of \$parent to prefer events
- Chagne use of \$children to check child type
- Fix overflow and interactive-tooltip position on scroll/resize
=> feat: v0.3.0 release

src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-icon/cv-icon.vue, src/components/cv-modal/cv-modal.vue
Remove console warnings no longer valid. 
Change storybook styling.
=> chore: tidy up and fix storybook

src/components/cv-file-uploader/cv-file-uploader-story.js, src/components/cv-file-uploader/cv-file-uploader.vue
Closes #95
Add missing parts for form uploader 
**Changed**
- CvFileUploader to include form item, label and helper text. Moved label prop to buttonLabel
=> fix: add missing file uploader parts

src/_storybook/utils/knobs-helper.js, src/components/cv-file-uploader/cv-file-uploader-story.js, src/components/cv-file-uploader/cv-file-uploader.vue
Closes #149 
Change file uploader to use v-model
**Changed**
- cv-file-uploader
=> feat: add v-model to file uploader

src/components/cv-checkbox/cv-checkbox.vue, src/components/cv-overflow-menu/cv-overflow-menu-item.vue, src/components/cv-overflow-menu/cv-overflow-menu-notes.md, src/components/cv-overflow-menu/cv-overflow-menu.vue, src/components/cv-search/_cv-search-inner-form-item.vue, src/components/cv-search/_cv-search-inner.vue, src/components/cv-search/cv-search.vue, src/components/cv-toolbar/cv-toolbar-divider.vue, src/components/cv-toolbar/cv-toolbar-notes.md, src/components/cv-toolbar/cv-toolbar-option.vue, src/components/cv-toolbar/cv-toolbar-search.vue, src/components/cv-toolbar/cv-toolbar-story.js, src/components/cv-toolbar/cv-toolbar-title.vue, src/components/cv-toolbar/cv-toolbar.vue, src/components/cv-tooltip/cv-interactive-tooltip.vue
Part of #51
Adds toolbar and springy toolbar search
**New**
- CvToolbar
- CvToolbarOption
- CvToolbarSearch
- CvToolbarTitle
- CvToolbarDivider
**Changed**
- CvSearch - added no form-item option and springy toolbar version
- CvOverflowMenu - Changed to accommodate non-CvOverflowMenuItem content.
=> feat: add toolbar

src/components/cv-data-table/cv-data-table-notes.md, src/components/cv-data-table/cv-data-table-story.js, src/components/cv-data-table/cv-data-table.vue
Part of  #51
Update table modifiers
**Changed**
- CvDataTable
- Added borderless and auto-width modifiers
- Corrected small modifier to short.
=> Table modifier changes

src/_storybook/views/sv-template-view/sv-template-view.vue
Fix storybook component view which was stretching everything.
=> fix: storyview

src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-number-input/cv-number-input-notes.md, src/components/cv-number-input/cv-number-input-story.js, src/components/cv-number-input/cv-number-input.vue
Changed number props to prefer invalidMessage over invalid and made it and helperText slops.
**Changed**
- CvNumberInput
=> Update number to slops

src/components/cv-accordion/cv-accordion-story.js, src/components/cv-breadcrumb/cv-breadcrumb-story.js, src/components/cv-button/cv-button-story.js, src/components/cv-code-snippet/cv-code-snippet-story.js, src/components/cv-form/cv-form-story.js, src/components/cv-inline-notification/cv-inline-notification-story.js, src/components/cv-link/cv-link-story.js, src/components/cv-list/cv-list-story.js, src/components/cv-loading/cv-loading-story.js, src/components/cv-modal/cv-modal-story.js, src/components/cv-slider/cv-slider-story.js, src/components/cv-toast-notification/cv-toast-notification-story.js, src/components/cv-toolbar/cv-toolbar-story.js
Tidy up linter warnings in prep for v1
**Changed**
- Removed linter warnings from 13 stories.
=> fix: linter warnings

README.md, package.json
Prep for v1.0.0-beta.0
**Changed**
- README.md
- package.json
=> chore: prep v1.0.0-beta.0

README.md, package.json, src/components/cv-content-switcher/cv-content-switcher-content.vue, src/components/cv-content-switcher/cv-content-switcher-store.js, src/components/cv-form/cv-form-notes.md
Fix typo in CvContentSwitcherContent
**Changed**
- CvContentSwitcherContent
=> chore: fix typo in release component

src/_storybook/utils/knobs-helper.js, src/components/cv-checkbox/cv-checkbox-story.js, src/components/cv-pagination/cv-pagination-story.js, src/components/cv-pagination/cv-pagination.vue, src/components/cv-radio-button/cv-radio-button.vue, src/components/cv-slider/cv-slider-story.js, src/components/cv-slider/cv-slider.vue, src/components/cv-tile/cv-tile.vue, src/mixins/radio-mixin.js
Removed use of Symbols in props as it caused problems in type checking in the minified compiled files.
**Changed**
- Storybook processing
- Checkbox story
- CvSlider
- CvPagination
- radio-mixin
=> fix: remove symbol usage and story fix

README.md, package.json, release.sh
v1.0.0-beta.2
**Added**
- added release script
**Changed**
- package.json
- Readme.md
=> chore: v1.0.0-beta.2 prep

src/components/cv-pagination/cv-pagination.vue
Removed console output from CvPagination
**Changed**
- CvPagination
=> chore: linter fixes

src/_storybook/utils/knobs-helper.js, src/components/cv-data-table/cv-data-table-story.js, src/components/cv-data-table/cv-data-table.vue, src/components/cv-pagination/cv-pagination.vue, src/components/cv-time-picker/cv-time-picker-story.js
Add header and footer to table, space for not internals of header and footer. 
**Changed**
- CvDataTable
=> feat: table footer and header

src/components/cv-data-table/cv-data-table-story.js, src/components/cv-data-table/cv-data-table.vue
Closes #
Add the ability to style columns and data
**Changed**
- CvDataTable
=> feat: header and footer for cv-data-table

src/components/cv-accordion/cv-accordion-item.vue, src/components/cv-code-snippet/_cv-code-snippet-multiline.vue, src/components/cv-code-snippet/_cv-feedback-button.vue, src/components/cv-content-switcher/cv-content-switcher-button.vue, src/components/cv-data-table/_cv-data-table-heading.vue, src/components/cv-inline-notification/cv-inline-notification.vue, src/components/cv-modal/cv-modal.vue, src/components/cv-overflow-menu/cv-overflow-menu-item.vue, src/components/cv-pagination/cv-pagination.vue, src/components/cv-search/_cv-search-inner.vue, src/components/cv-tile/_cv-tile-expandable.vue, src/components/cv-toast-notification/cv-toast-notification.vue
Add type="Button" to all buttons except cv-button which is left to the user. This prevents accidental form submission should a component be used in form.
=> chore: add button type values

README.md, package.json, src/components/cv-data-table/cv-data-table.vue
=> V1.0.0 beta.3

README.md, package.json
=> chore: v1.0.0-beta.4

src/components/cv-data-table/cv-data-table-action.vue, src/components/cv-data-table/cv-data-table-story.js, src/components/cv-data-table/cv-data-table.vue
Add table actions
**New**
- CvDataTableAction
**Changed**
- CvDataTable
=> feat: add table actions

src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-data-table/cv-data-table-story.js, src/components/cv-data-table/cv-data-table.vue, src/data-viz/cv-bar-graph/cv-bar-graph-story.js, src/data-viz/cv-bar-graph/cv-bar-graph.vue, src/data-viz/cv-gauge/cv-gauge-story.js, src/data-viz/cv-gauge/cv-gauge.vue, src/data-viz/cv-pie-chart/cv-pie-chart-story.js, src/data-viz/cv-pie-chart/cv-pie-chart.vue
Closes #
Added under review notices to CvDataTable, CvGauge, CvBarChart and CvPieChart.
=> Under construction

src/components/cv-data-table/cv-data-table-notes.md, src/components/cv-data-table/cv-data-table-story.js, src/components/cv-data-table/cv-data-table.vue
Closes #
Move pagination inside the CvDataTable component
**Changed**
- CvDataTable and story
=> chore: rework pagination

src/components/cv-data-table/cv-data-table-notes.md
Update table notes file to match updated table
=> Update table notes md

src/components/cv-data-table/cv-data-table-notes.md, src/components/cv-data-table/cv-data-table-row.vue, src/components/cv-data-table/cv-data-table-story.js, src/components/cv-data-table/cv-data-table.vue
Closes #51
Add overflow menu to CvDataTable
**Changed**
- CvDataTable
- CvDataTableRow
- CvDataTable story
- CvDataTable notes
=> feat: add overflow menu to table

README.md, package.json
V1 release prep
**Changed**
- README.md
- package.json
=> chore: v1 release prep

src/components/cv-checkbox/cv-checkbox-skeleton.vue, src/components/cv-checkbox/cv-checkbox-story.js
Adds `CvCheckboxSkeleton` components. Updates `CvCheckbox` story.
**New**
* `CvCheckboxSkeleton`
**Changed**
* `CvCheckbox` story
=> feat: add CvCheckboxSkeleton component

src/components/cv-code-snippet/cv-code-snippet-skeleton.vue, src/components/cv-code-snippet/cv-code-snippet-story.js
Adds `CvCodeSnippetSkeleton` components. Updates `CvCodeSnippet` story.
**New**
* `CvCodeSnippetSkeleton`
**Changed**
* `CvCodeSnippet` story
=> feat: add CvCodeSnippetSkeleton component

src/components/cv-dropdown/cv-dropdown-skeleton.vue, src/components/cv-dropdown/cv-dropdown-story.js
Adds `CvDropdownSkeleton` components. Updates `CvDropdown` story.
**New**
* `CvDropdownSkeleton`
**Changed**
* `CvDropdown` story
=> feat: add CvDropdownSkeleton component

src/components/cv-file-uploader/cv-file-uploader-skeleton.vue, src/components/cv-file-uploader/cv-file-uploader-story.js
Adds `CvFileUploadSkeleton` components. Updates `CvFileUpload` story.
**New**
* `CvFileUploadSkeleton`
**Changed**
* `CvFileUpload` story
=> feat: add CvFileUploadSkeleton component

README.md, package.json
**1.0.1**
- Removed setTimeout use
- Added Skeleton components for
- CvFileUpload
- CvDropdown
- CvCodeSnippet
- CvCheckbox
=> chore: v1.0.1 prep

src/components/cv-overflow-menu/cv-overflow-menu.vue
Closes #234
Prevent race between menu position and focus on first button.
=> Overflow menu fix

README.md, package.json
v1.0.2. release
- Add row-select-change and row-select-changes events to table
- Add rows-selected property to table
- Add use rows-selected with v-model for table
- Fix overflow menu issue #234
=> chore:v1.0.2

src/components/cv-code-snippet/_cv-code-snippet-multiline.vue, src/components/cv-code-snippet/_cv-code-snippet-oneline.vue, src/components/cv-code-snippet/cv-code-snippet-story.js
Closes #
Updates code snippet to carbon x behind feature flag
=> feat: carbon x code snippet

src/_storybook/views/sv-template-view/_sv-view.scss, src/_storybook/views/sv-template-view/sv-template-view.vue
Fixes CSS reset and tweaks storybook presentation
=> fix: storybook view and reset

src/components/cv-checkbox/_cv-checkbox-inner.vue
Closes #241 
Shows not-allowed cursor on disabled checkbox.
=> fix: checkbox hover when disabled

src/components/cv-button/cv-button-notes.md, src/components/cv-button/cv-button-story.js, src/components/cv-button/cv-button.vue, src/components/cv-content-switcher/cv-content-switcher-button.vue, src/components/cv-content-switcher/cv-content-switcher-notes.md, src/components/cv-content-switcher/cv-content-switcher-story.js
Closes #
Add carbon 10 component switcher
=> feat: add content switcher icon and carbonx

src/components/cv-radio-button/cv-radio-button.vue, src/components/cv-structured-list/_cv-structured-list-item-selectable.vue
CvRadioButton and CvStructuredListItemSelectable were missing inheritAttrs: false.
=> fix: add missing inherit attrs false

src/components/cv-date-picker/_cv-date-picker-inner-c10.vue, src/components/cv-date-picker/_cv-date-picker-inner.vue, src/components/cv-date-picker/cv-date-picker.vue
Part of #217 
Add carbon 10 version of date picker.
**Changed**
- CvDatePicker
=> feat: add carbon x date picker behind feature flag

src/components/cv-text-input/cv-text-input-notes.md, src/components/cv-text-input/cv-text-input-story.js, src/components/cv-text-input/cv-text-input.vue
Closes #214
Add password field options to CvTextInput
**Changed**
- CvTextInput
=> feat: add password type for input

src/components/cv-checkbox/cv-checkbox-story.js, src/components/cv-toggle/cv-toggle-story.js
Closes #225
Removes attempted storybook knob from array v-model for checkbox and toggle. It was causing problems for the notes.md files.
**Changed**
- CvToggle
- CvCheckbox
=> fix: change array model data to array from knob

src/_internal/_feature-flags.js, src/_storybook/views/sv-template-view/_sv-view.scss, src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-accordion/cv-accordion-story.js, src/components/cv-breadcrumb/cv-breadcrumb-story.js, src/components/cv-button/cv-button-story.js, src/components/cv-checkbox/cv-checkbox-story.js, src/components/cv-code-snippet/cv-code-snippet-story.js, src/components/cv-content-switcher/cv-content-switcher-story.js, src/components/cv-date-picker/cv-date-picker-story.js, src/components/cv-dropdown/cv-dropdown-story.js
Part of #217
Added switch for experimental (carbon 10) components.
**Changed**
- _internal/_feature-flags.js
- view templates
- some stories
=> Experimental switches

src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-content-switcher/cv-content-switcher-button.vue
Fix experimental spacing on the content switcher and experimental background.
**Changed**
- cv-content-switcher.vue
=> fix: content switcher icon spacing

CHANGELOG.md, README.md, package.json, release.sh, src/components/cv-checkbox/_cv-checkbox-inner-form-item.vue
=> chore: v1.1.0 release

src/components/cv-accordion/cv-accordion-story.js, src/components/cv-breadcrumb/cv-breadcrumb-story.js, src/components/cv-button/cv-button-story.js, src/components/cv-file-uploader/cv-file-uploader-story.js, src/components/cv-file-uploader/cv-file-uploader.vue
Part of #217
Add carbon x file uploader behind feature toggle.
Correct a couple of feature toggled stories.
=> feat: add carbonx file uploader

src/_storybook/utils/knobs-helper.js, src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-button/cv-button-story.js, src/components/cv-file-uploader/cv-file-uploader.vue, src/components/cv-form/cv-form-story.js, src/components/cv-link/cv-link-story.js, src/components/cv-list/cv-list-story.js, src/components/cv-modal/cv-modal-story.js, src/components/cv-modal/cv-modal.vue
Closes #
Add carbon x for form, link, list, modal. 
Updated danger button stories to remove danger--primary in experimental stories.
Added support to modal for data-modal-primary-focus
**Changed**
M       src/_storybook/utils/knobs-helper.js
M       src/_storybook/views/sv-template-view/sv-template-view.vue
M       src/components/cv-button/cv-button-story.js
M       src/components/cv-file-uploader/cv-file-uploader.vue
M       src/components/cv-form/cv-form-story.js
M       src/components/cv-link/cv-link-story.js
M       src/components/cv-list/cv-list-story.js
M       src/components/cv-modal/cv-modal-story.js
M       src/components/cv-modal/cv-modal.vue
=> feat: more carbon x

src/components/cv-data-table/cv-data-table-story.js
Part of #217
Add carbon x story for table
=> feat: add carbon x table

src/components/cv-inline-notification/cv-inline-notification-story.js, src/components/cv-inline-notification/cv-inline-notification.vue, src/components/cv-toast-notification/cv-toast-notification-story.js, src/components/cv-toast-notification/cv-toast-notification.vue
Part of #217
Add notifications for carbon x behind a feature flag
**Changed**
M       src/components/cv-inline-notification/cv-inline-notification-story.js
M       src/components/cv-inline-notification/cv-inline-notification.vue
M       src/components/cv-toast-notification/cv-toast-notification-story.js
M       src/components/cv-toast-notification/cv-toast-notification.vue
=> feat: notifications carbon x

src/components/cv-number-input/cv-number-input-story.js, src/components/cv-number-input/cv-number-input.vue
Part of #217 
Add carbon x number input updates behind feature flag.
**Changed**
m src/components/cv-number-input/cv-number-input-story.js
m src/components/cv-number-input/cv-number-input.vue
=> feat: add carbonx number input

package.json
**Changed**
- Change required node version in package.json to >=10.x
=> Change engines.node version to support v10 and higher

src/components/cv-content-switcher/cv-content-switcher.vue, src/components/cv-dropdown/_cv-dropdown-inner.vue, src/components/cv-dropdown/cv-dropdown-item.vue, src/components/cv-dropdown/cv-dropdown.vue, src/components/cv-tabs/cv-tabs.vue
Closes #262
The tab control was not functional when it switched to a dropdown below 768px width.
**Changed**
M       src/components/cv-content-switcher/cv-content-switcher.vue
M       src/components/cv-dropdown/_cv-dropdown-inner.vue
M       src/components/cv-dropdown/cv-dropdown-item.vue
M       src/components/cv-dropdown/cv-dropdown.vue
M       src/components/cv-tabs/cv-tabs.vue
=> Dropdown narrow

packages/core/src/components/cv-tabs/cv-tabs.vue, packages/core/vue.config.js
Closes #283 
Tweak tabs to work when using a component.
**Changed**
- cv-tabs.vue
=> fix: tabs with a bit of extra styling

storybook/stories/cv-time-picker/cv-time-picker-story.js
=> chore: tweak time picker story

packages/core/CHANGELOG.md
Move change log to packges/core
=> Move changelog

README.md, packages/core/README.md
Closes #
**New**
**Changed**
**Removed**
=> chore: update readme

README.md
Closes #
**New**
**Changed**
**Removed**
=> chore: fix library link

packages/core/src/components/cv-progress/cv-progress-step.vue
Part of #217
Fixes disabled state on progress step
=> fix: disabled state on progress step

README.md, storybook/.storybook/config.js
Change storybook github link. Add more getting started to top level README
=> chore: tweak storybook

README.md, packages/core/README.md, storybook/CHANGELOG.md
=> chore: alpha 1

packages/core/package.json, packages/core/src/components/cv-breadcrumb/cv-breadcrumb-item.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/data-viz/package.json, storybook/package.json, storybook/stories/cv-breadcrumb-story.js, storybook/stories/cv-data-table-story.js
Correct breadcrumb story and https to http in a couple of places
=> Breadcrumb story

README.md
Closes #
**New**
**Changed**
**Removed**
=> chore: test2

.circleci/manifest.yml
try v1-vue.carbondesignsystem.com
=> chore: try v1-vue

packages/core/package.json, packages/data-viz/package.json, storybook/.storybook/styles.scss, storybook/_storybook/views/sv-template-view/sv-versions.vue, storybook/_storybook/views/sv-template-view/sv-welcome.vue, storybook/package.json
=> Upstream v1

packages/core/src/components/cv-data-table/_cv-data-table-heading.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-dropdown/cv-dropdown-skeleton.vue
Correct v2 style classes found in data table and dropdown skeleton
=> fix: data table

storybook/_storybook/views/sv-template-view/sv-template-view.vue, storybook/stories/cv-inline-notification-story.js
Closes #311
Adds long sample text to the inline notification and sample view
=> chore: add longer inline notification sample

packages/core/src/components/cv-checkbox/cv-checkbox.vue, packages/core/src/components/cv-progress/cv-progress.vue, packages/core/src/mixins/check-mixin.js, storybook/stories/cv-checkbox-story.js
Closes #313
Add mixed to checkbox story and improve support.
**Changed**
M       packages/core/src/components/cv-checkbox/cv-checkbox.vue
M       packages/core/src/components/cv-progress/cv-progress.vue
M       packages/core/src/mixins/check-mixin.js
M       storybook/stories/cv-checkbox-story.js
=> Checkbox review

packages/core/src/components/cv-pagination/cv-pagination.vue, packages/core/src/components/cv-select/cv-select.vue, packages/core/src/public/demo.html, storybook/stories/cv-pagination-story.js
Closes #317
Fixes pagination styling and glitches for carbon 10
**Changed**
M       packages/core/src/components/cv-pagination/cv-pagination.vue
M       packages/core/src/components/cv-select/cv-select.vue
M       packages/core/src/public/demo.html
M       storybook/stories/cv-pagination-story.js
=> fix: carbon 10 pagination

packages/core/src/components/cv-select/cv-select.vue
Closes #319
Correct CvSelect layout and initial selected
**Changed**
packages/core/src/components/cv-select/cv-select.vue
=> fix: select layout and initial selected

packages/core/src/components/cv-file-uploader/cv-file-uploader-notes.md, packages/core/src/components/cv-file-uploader/cv-file-uploader.vue, storybook/stories/cv-file-uploader-story.js
Closes #323
Review updates to file uploader including adding invalid state
M       packages/core/src/components/cv-file-uploader/cv-file-uploader-notes.md
M       packages/core/src/components/cv-file-uploader/cv-file-uploader.vue
M       storybook/stories/cv-file-uploader-story.js
=> fix: file uploader review changes

packages/core/src/components/cv-data-table/_cv-data-table-heading.vue
Partof #321
Fix sort in the carbon x table
M       packages/core/src/components/cv-data-table/_cv-data-table-heading.vue
=> fix: table sort

packages/core/CHANGELOG.md
Beta updates to change log
Just the change log
=> chore: beta change log

packages/core/package.json, packages/core/src/components/cv-code-snippet/cv-code-snippet-notes.md, storybook/package.json, storybook/stories/cv-content-switcher-story.js
=> Correct code snippet story

README.md, storybook/stories/cv-link-story.js
=> chore: update link story with disabled

packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, storybook/_storybook/views/sv-template-view/sv-template-view.vue, storybook/stories/cv-overflow-menu-story.js
Adds upwards overflow menu option
M       storybook/_storybook/views/sv-template-view/sv-template-view.vue
M       storybook/stories/cv-overflow-menu-story.js
=> feat: add upwards overflow menu

packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue
Update content switcher to match core.
M  packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue
=> fix: update content switcher to match core

packages/core/src/components/cv-structured-list/_cv-structured-list-item-selectable.vue
Closes #365 
Change structured list selectable layout
**Changed**
- packages/core/src/components/cv-structured-list/_cv-structured-list-item-selectable.vue
=> fix: 365 layout of structured list selectable

packages/core/src/components/cv-toggle/cv-toggle.vue, storybook/stories/cv-toggle-story.js
Closes #370
Add label option to toggle. 
Add checkmarn inside small toggle.
M       packages/core/src/components/cv-toggle/cv-toggle.vue
M       storybook/stories/cv-toggle-story.js
=> fix: toggle layout 

packages/core/src/components/cv-search/cv-search.vue, packages/core/src/components/cv-toolbar/cv-toolbar-search.vue
Update search activation when clicking on icon in search and toolbar.
=> chore: update search

packages/core/src/components/cv-data-table/_cv-data-table-heading.vue, packages/core/src/components/cv-data-table/cv-data-table-action.vue, packages/core/src/components/cv-data-table/cv-data-table-row.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/stories/cv-data-table-story.js, storybook/stories/cv-toolbar-story.js
Fixes table toolbar styling
M       packages/core/src/components/cv-data-table/_cv-data-table-heading.vue
M       packages/core/src/components/cv-data-table/cv-data-table-action.vue
M       storybook/stories/cv-toolbar-story.js
=> fix: table layout

packages/core/src/components/cv-tabs/cv-tab.vue, packages/core/src/components/cv-tabs/cv-tabs-notes.md, packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/stories/cv-tabs-story.js
Closes #366 
Adds a story to toggle disabled state for one of the tabs. Adds 'disabled state' functionality to tabs component.
M packages/core/src/components/cv-tabs/cv-tab.vue
M packages/core/src/components/cv-tabs/cv-tabs-notes.md
M packages/core/src/components/cv-tabs/cv-tabs.vue
M storybook/stories/cv-tabs-story.js
=> feat: add disabled state for tabs component (carbon 10)

packages/core/src/components/cv-dropdown/_cv-dropdown-inner-c10.vue
Closes #377 
In _cv-dropdown-inner-c10 there was a vue error regarding multiple root nodes. This PR fixes it.
M packages/core/src/components/cv-dropdown/_cv-dropdown-inner-c10.vue
=> fix: multiple root nodes in _cv-dropdown-inner-c10

packages/core/src/components/cv-tag/cv-tag.vue, storybook/stories/cv-tag-story.js
Closes #367
Adds a filter kind to CvTag
**Changed**
- packages/core/src/components/cv-tag/cv-tag.vue
- storybook/stories/cv-tag-story.js
=> feat: add filter tag

README.md, docs/AtCarbonVue2.svg, storybook/_storybook/views/sv-template-view/sv-versions.vue, storybook/_storybook/views/sv-template-view/sv-welcome.vue
Update banner image, welcome and versions stories.
**Changed**
README.md
docs/AtCarbonVue2.svg
storybook/_storybook/views/sv-template-view/sv-versions.vue
storybook/_storybook/views/sv-template-view/sv-welcome.vue
=> chore: release prep

packages/core/package.json, packages/core/src/components/cv-dropdown/_cv-dropdown-inner-c10.vue, packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/package.json
Partial #385
**New**
**Changed**
packages/core/src/components/cv-dropdown/_cv-dropdown-inner-c10.vue
packages/core/src/components/cv-tabs/cv-tabs.vue
=> Cv tabs fix part1

packages/core/src/components/cv-data-table/cv-data-table-row.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/CHANGELOG.md, storybook/stories/cv-data-table-story.js
Table pagination
m packages/core/src/components/cv-data-table/cv-data-table-row.vue
m  packages/core/src/components/cv-data-table/cv-data-table.vue
m storybook/CHANGELOG.md
m storybook/stories/cv-data-table-story.js
=> Fix v2 table pagination

packages/core/package.json, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/package.json
Fix table number of items reset
m packages/core/src/components/cv-data-table/cv-data-table.vue
=> V2 table tweak

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-row.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/package.json, storybook/stories/cv-data-table-story.js
Adds expandable rows to the table
=> Table row expands

packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table-row.vue, storybook/stories/cv-data-table-story.js
Update story and notes to reflect expanded content slot changes.
=> chore: updated table row story

packages/core/CHANGELOG.md
=> chore: update changelog

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-tabs/cv-tab.vue, packages/core/src/components/cv-tabs/cv-tabs.vue, packages/data-viz/package.json, storybook/package.json
Fix CvTab disabling on tab creation.
M       packages/core/src/components/cv-tabs/cv-tab.vue
=> Disabled cv tab fix

packages/core/package.json, packages/data-viz/package.json, storybook/package.json
=> Add example project

storybook/stories/cv-time-picker-story.js
=> Fix time picker story

packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/stories/cv-data-table-story.js
Removed under-review tags from data table.
=> feat: data table ready

packages/core/src/components/cv-header/cv-header-global-action.vue, packages/core/src/components/cv-header/cv-header-menu-item.vue, packages/core/src/components/cv-header/cv-header-menu.vue, packages/core/src/components/cv-header/cv-header-name.vue, packages/core/src/components/cv-header/cv-header-nav.vue, packages/core/src/components/cv-header/cv-header-notes.md, packages/core/src/components/cv-header/cv-header.vue, packages/core/src/components/cv-header/cv-skip-to-content.vue, packages/core/src/components/cv-link/cv-link.vue, packages/core/src/mixins/link-mixin.js, storybook/.storybook/styles.scss, storybook/stories/cv-header-story.js
Part of #357
Add initial header implementation
=> Uishell header

packages/core/src/components/cv-tag/cv-tag-skeleton.vue, storybook/stories/cv-tag-story.js
Add CvTag skeleton component along with a story for it.
#167 
**New**
- packages/core/src/components/cv-tag/cv-tag-skeleton.vue
**Changed**
- storybook/stories/cv-tag-story.js
**Removed**
-
=> feat: add cv-tag-skeleton and a story for it

packages/core/src/components/cv-slider/cv-slider-skeleton.vue, storybook/stories/cv-slider-story.js
Add CvSlider skeleton component along with a story for it.
#167 
**New**
- packages/core/src/components/cv-slider/cv-slider-skeleton.vue
**Changed**
- storybook/stories/cv-slider-story.js
**Removed**
-
=> feat: add cv-slider-skeleton and a story for it

packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-tabs/cv-tabs.vue
Closes #423 
Corrects tab component use of dropdown component on a narrow screen.
=> fix: tab usage of dropdown when narrow

storybook/stories/cv-tag-story.js
Restore tag filter story removed during carbon x switch removal.
=> fix: restore filter tag story

packages/core/CHANGELOG.md
=> chore: release 2.3.0 prep

packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, packages/core/src/components/cv-toast-notification/cv-toast-notification.vue
Closes #435 
Correct aria-label and role as per issue.
=> fix: aria-label and role for 435

package.json, postcss.config.js, storybook/.storybook/.babelrc, storybook/.storybook/webpack.config.js, storybook/package.json
Corrects some build config inconsistencies / warnings.
=> chore: correct autoprefixer browserlist

packages/core/CHANGELOG.md
=> chore: v2-5-0 prep

packages/core/src/components/cv-ui-shell/_cv-side-nav-footer.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue, storybook/stories/cv-ui-shell-story.js
Add footer expand/hide
M       packages/core/src/components/cv-ui-shell/_cv-side-nav-footer.vue
M       packages/core/src/components/cv-ui-shell/cv-side-nav.vue
M       storybook/stories/cv-ui-shell-story.js
=> feat: expand hide side nave on footer click

.github/CONTRIBUTING.md
Fix minor typo.
**Changed**
- Minor typo on docs.
=> fix(docs): minor typo

packages/core/src/components/cv-ui-shell/cv-header-name.vue, storybook/stories/cv-ui-shell-story.js
Closes #446
- Adds white space between header prefix and name.
- Removes white space from story.
=> Eddybrando patch 1

packages/core/src/components/cv-modal/cv-modal-notes.md
Update notes for modal dialog.
=> chore: update modal notes with focus information

packages/core/src/components/cv-pagination/cv-pagination.vue
=> feat: add page to pagination event

packages/core/src/components/cv-text-input/cv-text-input.vue
The icon/button for showing and hiding password on input was positioned incorrectly in the component.
=> fix: password input layout

packages/core/CHANGELOG.md
=> chore: prep 2.6.1

packages/core/src/components/cv-ui-shell/cv-header-menu-button.vue
Correct header menu button active state.
=> fix: header menu button active

packages/core/src/components/cv-ui-shell/cv-header-menu-button.vue
Remove back slash added in error
=> fix: remove header menu button typo

packages/core/CHANGELOG.md
=> chore: 2.6.2 prep

packages/core/src/components/cv-checkbox/cv-checkbox.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-multi-select/cv-multi-select-notes.md, packages/core/src/components/cv-multi-select/cv-multi-select.vue, packages/core/src/components/cv-tag/cv-tag.vue, storybook/stories/cv-multi-select-story.js
First draft of #352
Add multi-select dropdown component
=> Feat multi select

packages/core/src/components/cv-multi-select/cv-multi-select.vue, storybook/stories/cv-multi-select-story.js
Part of #352
Adds selection feedback to multi select
=> feat: multi select feedback

packages/core/src/components/cv-pagination/cv-pagination-notes.md, packages/core/src/components/cv-pagination/cv-pagination.vue, storybook/stories/cv-pagination-story.js
Closes #453
Add scoped slots to deal with the need for some text being localised.
Specifically, this is for the text "X-Y of Z items" and "of N pages".
=> Slot pagination text

packages/core/CHANGELOG.md, packages/core/src/components/cv-multi-select/cv-multi-select-notes.md
=> chore: 2.7.0 prep

packages/core/package.json, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/package.json, storybook/stories/cv-data-table-story.js
Add scoped slot for tab rows selected text, this allows the user to specify how this text appears.
=> Table constructed string

packages/core/package.json, packages/core/src/components/cv-multi-select/cv-multi-select-notes.md, packages/core/src/components/cv-multi-select/cv-multi-select.vue, storybook/package.json, storybook/stories/cv-multi-select-story.js
Adds filterable multi-select and demonstrates use of value in story.
=> Filterable multi select

packages/core/src/components/cv-combo-box/cv-combo-box-notes.md, packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select-notes.md, packages/core/src/components/cv-multi-select/cv-multi-select.vue, storybook/_storybook/utils/knobs-helper.js, storybook/stories/cv-combo-box-story.js, storybook/stories/cv-multi-select-story.js, storybook/stories/cv-ui-shell-story.js
Add combo box and refine multi select
A       packages/core/src/components/cv-combo-box/cv-combo-box-notes.md
A       packages/core/src/components/cv-combo-box/cv-combo-box.vue
M       packages/core/src/components/cv-multi-select/cv-multi-select-notes.md
M       storybook/_storybook/utils/knobs-helper.js
A       storybook/stories/cv-combo-box-story.js
M       storybook/stories/cv-multi-select-story.js
M       storybook/stories/cv-ui-shell-story.js
=> Combo updates

packages/core/package.json, storybook/package.json
Correct main package file name.
=> Chore fix package main

packages/core/package.json, storybook/package.json
=> Revert package json

packages/core/src/components/cv-ui-shell/cv-content.vue, packages/core/src/components/cv-ui-shell/index.js, packages/core/src/index.js
=> feat: add CvContent

packages/core/CHANGELOG.md
=> chore: update change log

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-tabs/cv-tab.vue, packages/core/src/components/cv-tabs/cv-tabs.vue, packages/core/src/components/cv-ui-shell/cv-header-global-action.vue, packages/core/src/components/cv-ui-shell/cv-header-name.vue, storybook/package.json, storybook/stories/cv-tabs-story.js
M       packages/core/src/components/cv-tabs/cv-tab.vue
M       packages/core/src/components/cv-ui-shell/cv-header-global-action.vue
M       packages/core/src/components/cv-ui-shell/cv-header-name.vue
=> Tutorial fixes

packages/core/src/components/cv-data-table/_cv-data-table-heading.vue, packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-data-table/index.js, packages/core/src/index.js, storybook/stories/cv-data-table-story.js
Part of  #167
Add data table skeleton
M       packages/core/src/components/cv-data-table/_cv-data-table-heading.vue
A       packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue
M       packages/core/src/components/cv-data-table/index.js
M       packages/core/src/index.js
=> chore: add skeleton for data table

packages/core/package.json, packages/core/src/components/cv-data-table/_cv-data-table-heading.vue, packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue, packages/core/src/components/cv-pagination/cv-pagination.vue, storybook/package.json
Fix skeleton headings, component name and make pagination emit an initial 'change' event.
=> Table skeleton fix

packages/core/package.json, storybook/package.json
- @carbon/vue@2.12.0-rc.1
- storybook@2.12.0-rc.1
Closes #
**New**
**Changed**
**Removed**
=> chore: release 2.12.0.rc-1

packages/core/package.json, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/package.json
Make the table pagination pass though simpler and also pass through scoped slots.
=> Improve table pagination

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Correct name of cv-dropdown component
=> fix: cv-dropdown name

package.json, packages/core/__tests__/_helpers.js, packages/core/__tests__/cv-button.test.js, packages/core/package.json
Add more test, with test run hack.
=> chore: add button test

packages/core/src/components/cv-pagination/cv-pagination.vue
Closes #499 
Fix range text and page of pages when the number of items is zero.
=> fix: pagination range text and page of pages

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, storybook/stories/cv-combo-box-story.js
Closes #503 
Closes #504 
- Corrects color of clear button in combobox and multi select
- Corrects Combobox value updates which were causing the value rather than the label to appear
M       storybook/stories/cv-combo-box-story.js
=> Combo multi review

packages/core/src/mixins/check-mixin.js
Correct checkbox v-model to use true and false
=> fix: checkbox v-model setting undefined

packages/core/package.json, packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-header.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue, storybook/package.json
Fix header panel expand event emition
=> Fix panel expansion event

packages/core/package.json, packages/core/src/components/cv-ui-shell/cv-header-global-action.vue, packages/core/src/components/cv-ui-shell/cv-header-menu-button.vue, packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-header.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue, storybook/package.json
Adds v-model for header panel expansion
=> Header panel v model

packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue
Reduct side panel events by adjust raising of expand events so they only happen when the value changes.
=> chore: adjust header panel events

packages/core/package.json, packages/core/src/components/cv-modal/cv-modal.vue, storybook/package.json
Closes #
Change the excape reason to 'escape-press'
m packages/core/src/components/cv-modal/cv-modal.vue
=> Modal esc press case

packages/core/package.json, packages/core/src/components/cv-modal/cv-modal-notes.md, storybook/package.json
Update modal close notes
m packages/core/src/components/cv-modal/cv-modal-notes.md
=> Modal readme update

packages/core/src/components/cv-tile/cv-tile.vue, packages/core/src/mixins/check-mixin.js, storybook/stories/cv-tile-story.js
Correct selectable tile v-model behaviour
M	packages/core/src/components/cv-tile/cv-tile.vue
M	packages/core/src/mixins/check-mixin.js
M	storybook/stories/cv-tile-story.js
=> fix: selectable tile v-model

packages/core/package.json, packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, storybook/package.json
Closes #517 
Overflow only keeps focus if relatedTarget is null
=> Menu overflow fix again

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-breadcrumb/cv-breadcrumb-notes.md, packages/core/src/components/cv-breadcrumb/cv-breadcrumb-skeleton.vue, packages/core/src/components/cv-breadcrumb/cv-breadcrumb.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-file-uploader/cv-file-uploader-notes.md, packages/core/src/components/cv-file-uploader/cv-file-uploader.vue, packages/core/src/components/cv-inline-notification/cv-inline-notification-notes.md, packages/core/src/components/cv-inline-notification/cv-inline-notification.vue, packages/core/src/components/cv-search/cv-search-notes.md, packages/core/src/components/cv-search/cv-search.vue, packages/core/src/components/cv-tag/cv-tag-notes.md, packages/core/src/components/cv-tag/cv-tag.vue, packages/core/src/components/cv-tile/_cv-tile-selectable.vue, packages/core/src/components/cv-tile/cv-tile-notes.md, packages/core/src/components/cv-toast-notification/cv-toast-notification-notes.md, packages/core/src/components/cv-toast-notification/cv-toast-notification.vue, storybook/package.json, storybook/stories/cv-breadcrumb-story.js, storybook/stories/cv-data-table-story.js, storybook/stories/cv-file-uploader-story.js, storybook/stories/cv-inline-notification-story.js, storybook/stories/cv-search-story.js, storybook/stories/cv-tag-story.js, storybook/stories/cv-tile-story.js, storybook/stories/cv-toast-notification-story.js
Makes customisable some labels which are not currently.
M       packages/core/src/components/cv-breadcrumb/cv-breadcrumb-notes.md
M       packages/core/src/components/cv-breadcrumb/cv-breadcrumb-skeleton.vue
M       packages/core/src/components/cv-breadcrumb/cv-breadcrumb.vue
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-inline.vue
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-multiline.vue
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-oneline.vue
M       packages/core/src/components/cv-code-snippet/cv-code-snippet-notes.md
M       packages/core/src/components/cv-code-snippet/cv-code-snippet.vue
M …
=> Customisable strings

packages/core/package.json, packages/core/src/components/cv-modal/cv-modal-notes.md, packages/core/src/components/cv-modal/cv-modal.vue, storybook/package.json, storybook/stories/cv-modal-story.js
Closes #556
Adds primaryButtonDisabled attribute to match the react component functionality.
M       packages/core/src/components/cv-modal/cv-modal-notes.md
M       storybook/stories/cv-modal-story.js
=> Modal primary button disabled

lerna.json
Remove storybook from lerna publish
=> chore: lerna publish trim

lerna.json, packages/core/package.json
Correct lerna config go allow storybook build
=> Undo lerna config

packages/core/package.json, packages/core/src/components/cv-link/cv-link-notes.md, packages/core/src/mixins/link-mixin.js, storybook/stories/cv-link-story.js
Closes #563
M       packages/core/src/components/cv-link/cv-link-notes.md
M       packages/core/src/mixins/link-mixin.js
M       storybook/stories/cv-link-story.js
=> Feat link disabled

packages/core/package.json, packages/core/src/components/cv-date-picker/cv-date-picker.vue, storybook/package.json
Closes #561
Correct click on to date icon in the range picker so that the end date is the target. 
=> Date picker update

packages/core/package.json, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/package.json
Closes #569
Change date search field to stay expanded when not empty, as per carbon-components-react implementation.
=> Table search active

packages/core/__tests__/cv-button.test.js, packages/core/__tests__/cv-tag.test.js, packages/core/src/components/cv-button/cv-button.vue
Update button and tag tests.
Note click on button test not working. Due to use of $listeners? It works if a click event is explicitly emitted from the CvButton component
=> chore: update tag and button tests

packages/core/src/components/cv-dropdown/cv-dropdown-item.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue
Updates CvDropdown to carbon 10.6 
M       packages/core/src/components/cv-dropdown/cv-dropdown-item.vue
=> chore: update dropdown to carbon 10_6

packages/core/src/components/cv-link/cv-link-notes.md, packages/core/src/components/cv-link/cv-link.vue, storybook/stories/cv-link-story.js
Update ordered list to 10.7 style
M       packages/core/src/components/cv-link/cv-link-notes.md
M       packages/core/src/components/cv-link/cv-link.vue
M       storybook/stories/cv-link-story.js
=> feat: add inline link

packages/core/src/components/cv-list/cv-list-notes.md, packages/core/src/components/cv-list/cv-list.vue, storybook/stories/cv-list-story.js
Update list ordering to 10-7 design
M       packages/core/src/components/cv-list/cv-list-notes.md
M       packages/core/src/components/cv-list/cv-list.vue
M       storybook/stories/cv-list-story.js
=> feat: update list to 10-7 design

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
=> Canary release

package.json
Closes #
-
Add basic configuration for test coverage
M       package.json
`yarn test` will create a `coverage` folder with information about tests coverage for tested components.
=> feat: add basic setup for test coverage

packages/core/src/components/cv-tabs/cv-tabs.vue, packages/core/src/components/cv-tag/cv-tag.vue, packages/core/src/components/cv-text-input/cv-text-input.vue, packages/core/src/components/cv-toggle/cv-toggle-notes.md, packages/core/src/components/cv-toggle/cv-toggle.vue, storybook/stories/cv-toggle-story.js
Part of  #581 
10-7 updates
M       packages/core/src/components/cv-tag/cv-tag.vue
M       packages/core/src/components/cv-toggle/cv-toggle-notes.md
M       packages/core/src/components/cv-toggle/cv-toggle.vue
M       storybook/stories/cv-toggle-story.js
=> 10 7 updates to tabs, tags, text-input and toggle

packages/core/package.json, packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/package.json
Moire #611 
Remove use of children in favour of maintained tabs list
=> Tabs remove children use

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-tabs/cv-tabs-notes.md, packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/package.json
Closes #611
Add CvTabs property no-default-to-first
M       packages/core/src/components/cv-tabs/cv-tabs-notes.md
=> Tabs refinement

packages/core/src/components/cv-ui-shell/cv-header-menu.vue
Closes #581 
Add hover open to header menu
m packages/core/src/components/cv-ui-shell/cv-header-menu.vue
=> feat: add hover expand to headre menu

packages/core/src/components/cv-modal/cv-modal.vue
Closes #581 
Adds keyboard scroll to modal a suppresses background scroll
=> feat: keyboard modal scroll and surpasses background scroll

package.json
Add tests to build and pre-push to prevent breakages.
packages.json
=> Add test to build

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
=> chore(release): 2.17.0-canary.0

packages/core/__tests__/__snapshots__/cv-accordion.test.js.snap, packages/core/__tests__/__snapshots__/cv-wrapper.test.js.snap, packages/core/__tests__/cv-accordion.test.js, packages/core/__tests__/cv-wrapper.test.js
Add accordion and wrapper tests
A       packages/core/__tests__/__snapshots__/cv-accordion.test.js.snap
A       packages/core/__tests__/__snapshots__/cv-wrapper.test.js.snap
A       packages/core/__tests__/cv-accordion.test.js
A       packages/core/__tests__/cv-wrapper.test.js
=> feat: accordion and wrapper tests

packages/core/__tests__/__snapshots__/cv-checkbox.test.js.snap, packages/core/__tests__/__snapshots__/cv-tag.test.js.snap, packages/core/__tests__/__snapshots__/cv-toggle.test.js.snap, packages/core/__tests__/cv-accordion.test.js, packages/core/__tests__/cv-breadcrumb.test.js, packages/core/__tests__/cv-checkbox.test.js, packages/core/__tests__/cv-tabs.test.js, packages/core/__tests__/cv-tag.test.js, packages/core/__tests__/cv-toggle.test.js, packages/core/__tests__/cv-wrapper.test.js
Update toggle and tag tests to use snapshots
=> feat: update toggle and tag tests

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
Update changelog and release next canary
=> Release again

packages/core/CHANGELOG.md
=> feat: release 2-17

packages/core/CHANGELOG.md
=> chore: update changelog 2-17-1

packages/core/__tests__/__snapshots__/cv-tabs.test.js.snap, packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-dropdown/cv-dropdown-item.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-file-uploader/cv-file-uploader.vue, packages/core/src/components/cv-loading/cv-loading.vue, packages/core/src/components/cv-modal/cv-modal.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, packages/core/src/components/cv-search/cv-search.vue, packages/core/src/components/cv-tabs/cv-tabs.vue, packages/core/src/components/cv-ui-shell/_cv-side-nav-footer.vue, packages/core/src/components/cv-ui-shell/_cv-side-nav-link-text.vue, packages/core/src/components/cv-ui-shell/cv-content.vue, packages/core/src/components/cv-ui-shell/cv-header-menu.vue, packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-icon.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-items.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu-item.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue, packages/core/src/components/cv-ui-shell/cv-switcher-item-link.vue, packages/core/src/components/cv-ui-shell/cv-switcher-item.vue, packages/core/src/components/cv-ui-shell/cv-switcher.vue, packages/core/vue.config.js
Removal of <style> tags in favour of using computed or inline values. This is because unextracted style tags cause problems with SSR by accessing 'document'.
M       packages/core/__tests__/__snapshots__/cv-tabs.test.js.snap
M       packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue
M       packages/core/src/components/cv-dropdown/cv-dropdown-item.vue
M       packages/core/src/components/cv-file-uploader/cv-file-uploader.vue
M       packages/core/src/components/cv-loading/cv-loading.vue
M …
=> feat: enable use with ssr - nuxt

packages/core/CHANGELOG.md, packages/core/package.json
Release 2-18-0 with SSR support
=> Prep2 18 0

packages/core/CHANGELOG.md, packages/core/__tests__/__snapshots__/cv-tabs.test.js.snap, packages/core/__tests__/cv-tabs.test.js, packages/core/package.json
=> Prep2 19 0 canary 0

packages/core/__tests__/__snapshots__/cv-link.test.js.snap, packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap, packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-row.vue, packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-date-picker/cv-date-picker.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-modal/cv-modal.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, packages/core/src/components/cv-number-input/cv-number-input.vue, packages/core/src/components/cv-select/cv-select.vue, packages/core/src/components/cv-text-area/cv-text-area.vue, packages/core/src/components/cv-text-input/cv-text-input.vue, packages/core/src/components/cv-time-picker/cv-time-picker.vue, packages/core/src/components/cv-ui-shell/cv-header.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue, storybook/stories/cv-pagination-story.js
Change slot checks to boolean values so they show as true/false during debug/testing.
=> chore: make slot checks boolean

packages/core/__tests__/__snapshots__/cv-text-area.test.js.snap
Update text area snapshot as some attributes had moved.
=> chore: update text area snapshot

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
=> chore: Release prep2.19.0-canary.1

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
=> chore: release 2.19.0

packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap, packages/core/__tests__/cv-number-input.test.js, packages/core/src/components/cv-number-input/cv-number-input-notes.md, packages/core/src/components/cv-number-input/cv-number-input.vue, storybook/stories/cv-number-input-story.js
Closes #702 
Add decimal options to number input
M       packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap
M       packages/core/__tests__/cv-number-input.test.js
M       packages/core/src/components/cv-number-input/cv-number-input-notes.md
M       storybook/stories/cv-number-input-story.js
=> feat: floating point number input

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
=> Prep2 20 0 canary

packages/core/src/components/cv-data-table/cv-data-table.vue
Correct pagination attribute binding
=> fix: pagination property bind

packages/core/src/components/cv-inline-notification/cv-inline-notification.vue, packages/core/src/components/cv-toast-notification/cv-toast-notification.vue
m packages/core/src/components/cv-inline-notification/cv-inline-notification.vue
m packages/core/src/components/cv-toast-notification/cv-toast-notification.vue
=> chore: update to 10_7_4 dom

.github/PULL_REQUEST_TEMPLATE.md
Closes #
{{run "git diff --name-status master" and paste result here}}
=> Update PULL_REQUEST_TEMPLATE.md with smarter git diff

storybook/_storybook/views/sv-template-view/sv-versions.vue, storybook/_storybook/views/sv-template-view/sv-welcome.vue, storybook/package.json
Closes #712 
Fix excess horizontal scroll
M       storybook/_storybook/views/sv-template-view/sv-versions.vue
M       storybook/_storybook/views/sv-template-view/sv-welcome.vue
=> fix: excess horizontal scroll in welcome and versions pages

storybook/.storybook/config.js, storybook/.storybook/manager-head.html, storybook/_storybook/views/sv-template-view/sv-welcome.vue
Closes #712
M       storybook/.storybook/config.js
M       storybook/.storybook/manager-head.html
M       storybook/_storybook/views/sv-template-view/sv-welcome.vue
=> chore: a favicon, a title tweak, and a cheeky Vue icon

packages/core/src/components/cv-button/cv-button.vue
Removes temporary button icon issue.
m ackages/core/src/components/cv-button/cv-button.vue
=> chore: temp fix for cv-button icon

packages/core/__tests__/__snapshots__/cv-button.test.js.snap, packages/core/src/components/cv-button/cv-button.vue, packages/core/src/components/cv-button/cv-icon-button.vue
Make good the button pending @carbon/icons-vue updates
M       packages/core/__tests__/__snapshots__/cv-button.test.js.snap
=> chore: update button snapshots too

packages/core/__tests__/__snapshots__/cv-loading.test.js.snap, packages/core/__tests__/cv-loading.test.js
#182 
Add tests for CvLoading component.
A       packages/core/__tests__/__snapshots__/cv-loading.test.js.snap
A       packages/core/__tests__/cv-loading.test.js
=> test: add tests for cv-loading

packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/stories/cv-data-table-story.js
Closes #733
Makes individual columns sortable
=> chore: make individual columns sortable

packages/core/__tests__/cv-list.test.js
Closes #
Just deleted one comment I forgot.
M       packages/core/__tests__/cv-list.test.js
=> refactor: delete TODO comment I forgot to delete before

packages/core/package.json, storybook/package.json
=> chore: update package.json

packages/core/src/components/cv-code-snippet/_cv-feedback-button.vue, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-structured-list/cv-structured-list-notes.md
Tidies up some typos
M       packages/core/src/components/cv-code-snippet/_cv-feedback-button.vue
M       packages/core/src/components/cv-structured-list/cv-structured-list-notes.md
=> Jungle badger master

packages/core/src/components/cv-date-picker/cv-date-picker.vue
Date picker was raising an error on change when value was not supplied as a property
m  packages/core/src/components/cv-date-picker/cv-date-picker.vue
=> fix: date picker change when value not supplied

packages/core/CHANGELOG.md, packages/core/package.json
=> Prep canary2 20 0 canary 2

packages/core/package.json, storybook/package.json
=> 2.20.0-canary.2

packages/core/CHANGELOG.md
Update changelog for 2.20 release
m packages/core/CHANGELOG.md
=> chore: 2.20.0 release prep

packages/core/package.json, storybook/package.json
=> chore: @carbon/vue@2.20.0

package.json, packages/core/__tests__/__snapshots__/cv-loading.test.js.snap, packages/core/__tests__/cv-loading.test.js, packages/core/src/components/cv-loading/cv-loading.vue
Fix tests and build
M       package.json
M       packages/core/__tests__/__snapshots__/cv-loading.test.js.snap
M       packages/core/__tests__/cv-loading.test.js
M       packages/core/src/components/cv-loading/cv-loading.vue
M       storybook/stories/cv-loading-story.js
=> chore: fix build

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
Fix release changelog and dodgy versioning
m packages/core/CHANGELOG.md
=> Release prep

packages/core/package.json, storybook/package.json
=> chore(release): publish %s

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
Pub canary
m packages/core/CHANGELOG.md
m packages/core/package.json
m storybook/package.json
=> Pub canary

packages/core/src/components/cv-number-input/cv-number-input-notes.md, packages/core/src/components/cv-number-input/cv-number-input.vue, storybook/stories/cv-number-input-story.js
Reworked number use to use stepUp and stepDown methods of input.
M       packages/core/src/components/cv-number-input/cv-number-input-notes.md
M       storybook/stories/cv-number-input-story.js
=> Another number input

packages/core/src/components/cv-date-picker/cv-date-picker-notes.md, packages/core/src/components/cv-date-picker/cv-date-picker.vue
Fix date picker initial value and update notes to use cal-options
M       packages/core/src/components/cv-date-picker/cv-date-picker-notes.md
=> fix: date picker initial value and doc

packages/core/src/components/cv-number-input/cv-number-input.vue
Disable number input buttons when the control is disabled.
=> fix: number input disabled buttons

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
=> Publish 2.20.1

packages/core/src/components/cv-modal/cv-modal-notes.md, packages/core/src/components/cv-modal/cv-modal.vue, packages/core/src/components/cv-search/cv-search-notes.md, packages/core/src/components/cv-search/cv-search.vue, packages/core/src/components/cv-select/cv-select.vue, packages/core/src/components/cv-tabs/cv-tabs-notes.md, packages/core/src/components/cv-tabs/cv-tabs.vue, packages/core/src/components/cv-tag/cv-tag.vue, storybook/stories/cv-modal-story.js, storybook/stories/cv-search-story.js, storybook/stories/cv-tabs-story.js, storybook/stories/cv-tabs-story.scss
Updates remaining components to V10.9 of carbon components
{{run "git diff --name-status $(git merge-base head master)" and paste result here}}
=> V10 7to10 9part2

packages/core/__tests__/__snapshots__/cv-tabs.test.js.snap, packages/core/__tests__/__snapshots__/cv-tag.test.js.snap, packages/core/__tests__/cv-number-input.test.js
=> fix: tests failing after recent update

packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/stories/cv-tabs-story.js
Closes #775 
Addresses an issue where a tab is being added and selected. Added to story to demonstrate.
=> Tab update

packages/core/__tests__/cv-tabs.test.js, packages/core/src/components/cv-tabs/cv-tabs.vue
Correct test and new index on removing a tab.
M       packages/core/__tests__/cv-tabs.test.js
=> Tab test fix

packages/core/CHANGELOG.md, packages/core/package.json, storybook/package.json
Publish canary 2.20.1-canary.0
=> Prep canary

storybook/.storybook/webpack.config.js
M       storybook/.storybook/webpack.config.js
=> fix: favicon copy path

packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap, packages/core/__tests__/cv-number-input.test.js
Correct cv-number-input snapshot and add mobile variation
=> fix: number input snapshot

.circleci/config.yml, package.json
Eliminate the storybook build progress messages that just fill up the CI log
M       .circleci/config.yml
M       package.json
=> reduce CI messages

packages/core/src/components/cv-ui-shell/cv-ui-shell-notes.md, storybook/stories/cv-ui-shell-story.js
Update UI shell doc to add the expanded property on side nav menu item.
=> chore: update ui shell doc

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-modal/cv-modal.vue
=> chore: release canary 2.22.0-canary.1

packages/core/src/components/cv-accordion/cv-accordion-item.vue, packages/core/src/components/cv-accordion/cv-accordion-notes.md, packages/core/src/components/cv-accordion/cv-accordion.vue, storybook/stories/cv-accordion-story.js
Closes #809
Adds change event to CvAccordion and a state value via which the open set can be updated.
m   packages/core/src/components/cv-accordion/cv-accordion-item.vue 
m   packages/core/src/components/cv-accordion/cv-accordion-notes.md
m   packages/core/src/components/cv-accordion/cv-accordion.vue
m   storybook/stories/cv-accordion-story.js
=> feat: add accordion change event and state value

packages/core/CHANGELOG.md, packages/core/package.json
=> Release canary 2.23.0-canary.0

packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue
Related to  #833
Apply IE11 support scroll fix to interactive tooltip 
m  packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue 
m  packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue
=> fix: interactive tooltip position on ie11

packages/core/CHANGELOG.md, packages/core/package.json
Publish canary
M	packages/core/CHANGELOG.md
M	packages/core/package.json
=> Publish canary

packages/core/CHANGELOG.md, packages/core/package.json
=> Publish 2.23.1

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Makes a change to ensure placeholder property updates are reflected in the DOM.
m packages/core/src/components/cv-dropdown/cv-dropdown.vue
=> fix: dropdown placeholder updates

packages/core/__tests__/_helpers.js
Remove await's that did nothing.
m   packages/core/__tests__/_helpers.js
=> chore: remove spurious await from mount helper

packages/core/CHANGELOG.md, packages/core/package.json
=> Canary 2.23.2-canary.0

packages/core/CHANGELOG.md, packages/core/package.json
=> Release 2.23.2

packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-number-input/cv-number-input-notes.md, packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/stories/cv-data-table-story.js
Warn against use of duplicate IDs for cv-data-table-row and cv-tab
=> chore: warn on duplicate ids for tab or tablerow

.circleci/config.yml, packages/core/package.json
Attempt to fix deploy stage of build
=> fix: deploy step

packages/core/src/components/cv-data-table/cv-data-table-notes.md, storybook/stories/cv-data-table-story.js
Shows use of row expanded in story and notes in notes.
=> chore: show use of row expaned in story

packages/core/src/components/cv-dropdown/cv-dropdown.vue, storybook/stories/cv-dropdown-story.js
Closes #870
Ensure presentation on Dropdown is of HTML caption not text as was being presented.
M       storybook/stories/cv-dropdown-story.js
=> fix: dropdown value presentation

packages/core/CHANGELOG.md, packages/core/package.json
=> Release 2.24.1

.circleci/config.yml
Update circle ci node version
M       .circleci/config.yml
=> fix: circle ci node version

packages/core/__tests__/cv-loading.test.js
=> chore: try disabling functional tests for loading

package.json, packages/core/__tests__/cv-loading.test.js
M       package.json
M       packages/core/__tests__/cv-loading.test.js
=> fix: try just 5 workers on test

packages/core/src/components/cv-multi-select/cv-multi-select.vue
=> fix: multi select expand

packages/core/__tests__/__snapshots__/cv-inline-notification.test.js.snap, packages/core/__tests__/__snapshots__/cv-toast-notification.test.js.snap, packages/core/__tests__/cv-inline-notification.test.js, packages/core/__tests__/cv-tag.test.js, packages/core/__tests__/cv-toast-notification.test.js
Correct snapshots and tests following recent updates.
=> chore: update tests to match 10-11-2 updates

packages/core/src/components/cv-button/cv-icon-button.vue
Correct button snapshot following icon only change
=> fix: button snapshot

packages/core/CHANGELOG.md, packages/core/package.json
=> 2 26 canary

packages/core/CHANGELOG.md, packages/core/package.json, storybook/stories/cv-data-table-story.js
=> Canary 2.27.0-canary.0

packages/core/CHANGELOG.md, packages/core/package.json
=> Release2 27 0

packages/core/src/components/cv-accordion/_cv-accordion-item-skeleton.vue, packages/core/src/components/cv-accordion/cv-accordion-item.vue, packages/core/src/components/cv-accordion/cv-accordion-skeleton.vue, packages/core/src/components/cv-accordion/cv-accordion.vue
Use carbonPrefix in CvAccordion
M       packages/core/src/components/cv-accordion/_cv-accordion-item-skeleton.vue
M       packages/core/src/components/cv-accordion/cv-accordion-item.vue
M       packages/core/src/components/cv-accordion/cv-accordion-skeleton.vue
M       packages/core/src/components/cv-accordion/cv-accordion.vue
=> chore: use carbon prefix in accordion

package.json, packages/core/package.json
Lower node engine requirement to 10 as it is still in use.
=> chore: lower node engine requirement

packages/core/CHANGELOG.md, packages/core/package.json
=> Release 2.27.1

packages/core/src/components/cv-combo-box/cv-combo-box.vue
Closes #923
Correct misspelling of $attrs.
=> fix: issue 923 comboBox attrs name

packages/core/src/components/cv-form/cv-form.vue
Closes #924 
Pass $listeners to form to allow @submit.prevent to be prevented.
M       packages/core/src/components/cv-form/cv-form.vue
=> fix: issue 924 passing $listeners to cv-form

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue
Closes #927
Put focus back on dropdown after selection or escape
=> fix: 927 dropdown focus reset post selection

packages/core/CHANGELOG.md, packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap, packages/core/__tests__/__snapshots__/cv-text-area.test.js.snap, packages/core/__tests__/__snapshots__/cv-text-input.test.js.snap, packages/core/package.json
=> Pub 2.30.0-canary.1

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue
The previous fix caused initial load to fail.
=> fix: combo and multi empty class

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue
=> fix: empty space on combo and multi

packages/core/src/components/cv-progress/cv-progress-step.vue
Closes #971
Correct use of carbonPrefix
m  packages/core/src/components/cv-progress/cv-progress-step.vue
=> fix: progress step carbonPrefix

packages/core/CHANGELOG.md, packages/core/package.json
=> Publish 2.30.1

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-dropdown/cv-dropdown.vue
=> Publish fix drop as canary

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Part of #989
Fixes dark mode display of dropdown
m  packages/core/src/components/cv-dropdown/cv-dropdown.vue
=> Fix drop dark

.circleci/config.yml
Attempt to fix storybook deploy
=> chore: fix deploy

.circleci/config.yml
Closes #
{{run "git diff --name-status $(git merge-base head master)" and paste result here}}
=> Deploy fix

.circleci/config.yml
Closes #
{{run "git diff --name-status $(git merge-base head master)" and paste result here}}
=> Again deploy

packages/core/CHANGELOG.md, packages/core/package.json
Promote canary to release which closes #1007
`
=> Chore release

packages/core/CHANGELOG.md, packages/core/package.json
=> Publish 2.34.0-canary.0

README.md, packages/core/CHANGELOG.md, packages/core/package.json
Update changelog and release Canary
=> Release 2.34.0-canary.1

packages/core/__tests__/__snapshots__/cv-structured-list.test.js.snap, packages/core/__tests__/cv-structured-list.test.js
#182
Add tests for CvStructuredList, CvStructuredListItem, CvStructuredListHeading and CvStructuredListData components.
A       packages/core/__tests__/__snapshots__/cv-structured-list.test.js.snap
A       packages/core/__tests__/cv-structured-list.test.js
=> test: add tests for cv-structured-list component

packages/core/src/components/cv-button/button-mixin.js
Closes #
{{run "git diff --name-status $(git merge-base head master)" and paste result here}}
=> fix(server): cv-button default color error issue

packages/core/src/components/cv-multi-select/cv-multi-select.vue
Closes [#1095](https://github.com/carbon-design-system/carbon-components-vue/issues/1095)
Fixes the behavior where each other click to open the cv-multi-select component hide the first element
=> Fix scroll behavior

packages/core/src/components/cv-svg/_cv-svg.vue
Removes unused code.
, packages/core/src/components/cv-svg/_cv-svg.vue
=> chore: remove unused CvWrapper

packages/v3/package.json, packages/v3/src/components/CvButton/CvButton.stories.js, packages/v3/src/components/CvButton/CvButton.vue, packages/v3/src/components/CvButton/CvButtonCommon.js, packages/v3/src/components/CvButton/CvIconButton.stories.js, packages/v3/src/components/CvButton/CvIconButton.vue, packages/v3/src/components/CvButton/__tests__/CvButtonCommon.spec.js, packages/v3/src/components/CvButton/__tests__/CvIconButton.spec.js, packages/v3/src/components/CvSvg/_CvSvg.vue, packages/v3/src/components/CvSvg/__tests__/CvSvg.spec.js, packages/v3/src/components/CvSvg/__tests__/_TestIcon.vue, packages/v3/src/components/CvSvg/__tests__/test-svg.svg, packages/v3/src/global/__tests__/storybook-utils.spec.js, packages/v3/src/global/storybook-utils.js
Adds 100% test for storybook utils
M       packages/v3/package.json
M       packages/v3/src/components/CvButton/CvButton.stories.js
M       packages/v3/src/components/CvButton/CvIconButton.stories.js
A       packages/v3/src/global/__tests__/storybook-utils.spec.js
M       packages/v3/src/global/storybook-utils.js
=> chore: add test to storybook utils

packages/v3/src/components/CvButton/CvButton.stories.js, packages/v3/src/components/CvButton/CvButton.vue, packages/v3/src/components/CvButton/CvButtonSet.stories.js, packages/v3/src/components/CvButton/CvButtonSet.vue, packages/v3/src/components/CvButton/CvIconButton.stories.js, packages/v3/src/components/CvButton/CvIconButton.vue, packages/v3/src/components/CvButton/__tests__/CvButton.spec.js, packages/v3/src/components/CvButton/__tests__/CvButtonSet.spec.js, packages/v3/src/components/CvButton/index.js
Add CvButtonSet 
M       packages/v3/src/components/CvButton/CvButton.vue
A       packages/v3/src/components/CvButton/CvButtonSet.vue
M       packages/v3/src/components/CvButton/CvIconButton.vue
M       packages/v3/src/components/CvButton/__tests__/CvButton.spec.js
A       packages/v3/src/components/CvButton/__tests__/CvButtonSet.spec.js
M       packages/v3/src/components/CvButton/index.js
=> feat: add CvButtonSet

packages/v3/src/components/CvButton/CvIconButton.stories.js
Minor update to story
m packages/v3/src/components/CvButton/CvIconButton.stories.js
=> chore: v3 tweak icon button story

packages/v3/src/components/CvAccordion/CvAccordion.stories.js, packages/v3/src/components/CvButton/CvButton.stories.js, packages/v3/src/components/CvButton/CvButtonSet.stories.js, packages/v3/src/components/CvButton/CvIconButton.stories.js, packages/v3/src/components/CvButton/sbBtnPrefix.js, packages/v3/src/components/CvTag/CvTag.stories.js, packages/v3/src/components/CvTag/CvTag.vue, packages/v3/src/global/storybook-utils/index.js, packages/v3/src/global/storybook-utils/sbCompPrefix.js
A little refactor to use common code for Storybook prefixes.
Also adds CvTag accordion
=> chore: little refactor

.github/PULL_REQUEST_TEMPLATE.md
Contributes to # N/A
Simplify the PR template 
Seemed silly to keep posting lists of files changed when it's in the PR.
Ran `yarn format`
=> chore: simplify pull request template

packages/v3/src/components/CvButton/CvButtonSet.stories.js, packages/v3/src/components/CvButton/sbBtnPrefix.js, packages/v3/src/components/CvTag/__tests__/CvTag.spec.js, packages/v3/src/global/storybook-utils/__tests__/story-source-code.js, packages/v3/src/global/storybook-utils/story-source-code.js
Contributes to #1020 
Fix existing tests.
Tests were failing
Ran the tests ;-)
=> fix: v3 tests

packages/core/src/components/cv-button/button-mixin.js, packages/core/src/components/cv-button/cv-button-notes.md, storybook/stories/cv-button-story.js
Contributes to #1146
Added the missing button kinds
Parity with Carbon Design System
Storybook
=> Fix CvButton missing kinds

packages/v3/package.json, packages/v3/yarn.lock
Added `@vueuse/core` as a dependency for v3
It seems like a great collection of re-usable Vue tools, which will lower our own implementation complexity.
=> [v3] chore(deps): add @vueuse/core dependency

packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap, packages/core/src/components/cv-number-input/cv-number-input.vue
Contributes to #1165 
Update the number input
It was using an old version of the DOM
Storybook
=> feat: update number input to 10-30

packages/v3/.storybook/manager.js, packages/v3/.storybook/theme.js, packages/v3/README.md, packages/v3/package.json, storybook/_storybook/views/sv-template-view/sv-versions.vue, storybook/_storybook/views/sv-template-view/sv-welcome.vue
Contributes to #1020 
- Updated the Vue 2 welcome and versions to include Vue 3
- Updated theme in Vue 3 storybook changing title and URL.
Visibility and links to source code from the storybook.
Ran up Vue 2 and 3 storybooks
=> chore: update with Vue 3 info

.circleci/config.yml
Fixed deploy of Carbon/Vue2 which was broken by switch to "main" bracnh.
=> fix: deploy of v2

packages/core/src/components/cv-form/cv-form-group.vue, packages/core/src/components/cv-form/cv-form-notes.md, storybook/.storybook/config.js, storybook/stories/cv-form-story.js, storybook/stories/cv-tile-story.js
Contributes to #436 
Update CvFormGroup
Storybook
=> chore: update form group to 1030

packages/core/src/components/cv-button/cv-icon-button.vue, packages/core/src/components/cv-ui-shell/cv-header-global-action.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-divider.vue, packages/core/src/components/cv-ui-shell/cv-ui-shell-notes.md, packages/core/src/components/cv-ui-shell/index.js, packages/core/src/index.js, storybook/stories/cv-ui-shell-story.js
Contributes to #1159 
Updated UiShell to 10.30 adding tooltips to global actions and CvSideNavDivider.
Update to 10.30
Storybook.
=> feat: update ui shell to 1030

packages/core/CHANGELOG.md, packages/core/package.json, packages/v3/package.json
Closes #436 
Update component dom to 1030.
Out of date
Storybook and test
=> Release canaray2 38 0

packages/core/CHANGELOG.md, packages/core/package.json, packages/v3/package.json
Closes #436 
Update component dom to 1030.
Out of date
Storybook and test
=> Release canaray2 38 0.1

packages/core/CHANGELOG.md, packages/core/package.json, packages/v3/package.json
Contributes to #1165 
Promote Canary
No issues raised against canary
=> Release 2.38.0

packages/core/src/components/cv-modal/cv-modal.vue
Contributes to #1199
Adjusted the event emitted in the secondary button click.
To fix the component's behavior.
N/A
=> Fix event emitted by the `secondary` button

packages/core/CHANGELOG.md, packages/core/package.json, packages/v3/package.json
=> Fix release

packages/core/src/components/cv-modal/cv-modal.vue, storybook/stories/cv-modal-story.js
Fix modal button stories
Did not show click events working
Tested in storybook.
=> fix: modal buttons and stories

packages/core/CHANGELOG.md, packages/core/package.json, packages/v3/package.json
=> 2.38.2release

packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/stories/cv-data-table-story.js
Closes #1224
Add staticWidth to storybook and the data table notes.
PR 1224 was missing this information
Ran storybook.
=> Metonym data table static width

.github/workflows/update.yml
=> chore: correct update script

packages/core/src/components/cv-file-uploader/cv-file-uploader.vue
Contributes to #1316 
Fix file uploader accessibility issue
=> fix: file uploader accessibility issue

.github/workflows/pr.yml, packages/core/README.md
Helps ensure changelog has consistent formatting.
Currently not clear why all changes were made.
No.
=> chore: verify PR titles for CHANGELOG updates

packages/core/README.md
Fixed badges in package readme.
Badges in package @carobn/vue README were failing
Previewed markdown
=> fix: reaadme badges

packages/core/src/carbon.yml, packages/core/src/thumbnails/inline-notification.svg, packages/core/src/thumbnails/skeleton-text.svg, packages/core/src/thumbnails/toast-notification.svg
Closes: https://github.com/carbon-design-system/carbon-platform/issues/517
Indexes Carbon Components Vue for Carbon Platform
=> chore(INDEX): index carbon components vue

packages/core/src/carbon.yml
Updated Library name `Carbon Components Vue` -> `Carbon Vue` https://github.com/carbon-design-system/carbon-platform/issues/832
=> chore: update library name

.storybook/manager-head.html, .storybook/theme.js, src/components/CvSelect/CvSelect.stories.mdx, src/components/CvSelect/CvSelect.vue, src/components/CvSelect/CvSelectOptgroup.vue, src/components/CvSelect/CvSelectOption.vue, src/components/CvSelect/__tests__/CvSelect.spec.js, src/components/CvSelect/index.js
Contributes to #1377
Port cv-select to v3. Include mdx story and tests
=> feat: add CvSelect to vNext

.storybook/Welcome/__welcome-story.js, .storybook/main.js, .storybook/preview.js, src/components/CvBreadcrumb/__tests__/CvBreadcrumb.spec.js, src/components/CvBreadcrumb/__tests__/CvBreadcrumbSkeleton.spec.js, src/components/CvCheckbox/CvCheckbox.stories.js, src/components/CvCheckbox/CvCheckbox.vue, src/components/CvComboBox/CvComboBox.stories.js, src/components/CvComboBox/CvComboBox.vue, src/components/CvContentSwitcher/CvContentSwitcher.stories.mdx, src/components/CvContentSwitcher/CvContentSwitcher.vue, src/components/CvContentSwitcher/CvContentSwitcherButton.vue, src/components/CvCopyButton/CvCopyButton.stories.js, src/components/CvLoading/CvLoading.stories.js, src/components/CvLoading/CvLoading.vue, src/components/CvLoading/__tests__/CvLoading.spec.js, src/components/CvOverflowMenu/CvOverflowMenu.stories.mdx, src/components/CvOverflowMenu/CvOverflowMenu.vue, src/components/CvOverflowMenu/CvOverflowMenuItem.vue, src/components/CvOverflowMenu/__tests__/CvOverflowMenu.spec.js, src/components/CvOverflowMenu/index.js, src/components/CvPagination/CvPagination.stories.mdx, src/components/CvPagination/CvPagination.vue, src/components/CvSelect/CvSelect.stories.mdx, src/components/CvSelect/CvSelect.vue, src/components/CvSelect/CvSelectOptgroup.vue, src/components/CvSelect/CvSelectOption.vue, src/global/component-utils/event-bus.js
Contributes to #1385 
Port overflow menu to v3
Unit tests included
=> feat: overflow menu v3

packages/core/src/components/cv-tabs/cv-tabs.vue
As discussed, we need to fix tab refresh when first clicking issue. Thanks.
=> fix: add type="button" for tabs

.github/workflows/stale.yml
=> chore: add stalebbot config

packages/core/CHANGELOG.md, packages/core/src/components/cv-tag/cv-tag.vue, packages/v3/CHANGELOG.md
=> fix: Tag close type button

packages/core/src/components/cv-data-table/cv-data-table.vue
Contributes to #1389
Change search box input tag role to searchbox
Fix accessibility report check on multiple search roles
Run accessibility test after alteration
=> fix(cv-data-table): fix searchbox role

.github/workflows/deploy-vue-storybook.yml
Updated storybook deploy action node and action setup version
=> chore: update storybook deploy action

main.js, package.json, src/components/CvButton/CvIconButton.vue, src/components/CvUIShell/CvHeader.vue, src/components/CvUIShell/CvHeaderGlobalAction.vue, src/components/CvUIShell/CvHeaderMenu.vue, src/components/CvUIShell/CvHeaderMenuButton.vue, src/components/CvUIShell/CvHeaderMenuItem.vue, src/components/CvUIShell/CvHeaderName.vue, src/components/CvUIShell/CvHeaderNav.vue, src/components/CvUIShell/CvHeaderPanel.vue, src/components/CvUIShell/CvSideNav.vue, src/components/CvUIShell/CvSideNavIcon.vue, src/components/CvUIShell/CvSideNavItems.vue, src/components/CvUIShell/CvSideNavLink.vue, src/components/CvUIShell/CvSideNavMenu.vue, src/components/CvUIShell/CvSideNavMenuDivider.vue, src/components/CvUIShell/CvSideNavMenuItem.vue, src/components/CvUIShell/CvSkipToContent.vue, src/components/CvUIShell/CvSwitcher.vue, src/components/CvUIShell/CvSwitcherItem.vue, src/components/CvUIShell/CvSwitcherItemLink.vue, src/components/CvUIShell/CvUIShell.stories.mdx, src/components/CvUIShell/_CvSideNavFooter.vue, src/components/CvUIShell/_CvSideNavLinkText.vue, src/components/CvUIShell/__tests__/CvHeader.spec.js, src/use/cvLink.js
Contributes to #1405 
Port ui shell components to Vue 3
Added basic tests but more are needed. Will more on more tests in a future issue.
=> feat: UI shell for Vue 3

src/components/CvGrid/CvColumn.vue, src/components/CvGrid/CvGrid.vue, src/components/CvGrid/CvRow.vue, src/components/CvGrid/GvGrid.stories.mdx, src/components/CvGrid/_SbContainer.vue, src/components/CvGrid/__tests__/CvGrid.spec.js
Contributes to #1412 
Port grid to Vie3
=> feat: add grid, row, & column with tests and story

main.js, src/components/CvAccordion/CvAccordionSkeleton.vue, src/components/CvAccordion/_CvAccordionItemSkeleton.vue, src/components/CvCheckbox/CvCheckbox.vue, src/components/CvDataTable/CvDataTable.vue, src/components/CvDataTable/CvDataTableHeading.vue, src/components/CvDataTable/CvDataTableRow.vue, src/components/CvDataTable/_CvDataTableRowInner.vue, src/components/CvEmpty/CvEmpty.vue, src/components/CvGrid/CvColumn.vue, src/components/CvGrid/_cvColumnValidation.js, src/components/CvPagination/CvPagination.vue
Created a sample project, "hello-carbon-vue3",  that I will publish soon. Made changes and fixed bugs based on actual use of the components.
Shakedown cruise
Real-world testing
=> fix: fixes to components based on actual use in an example project

package.json, src/components/CvDataTable/__tests__/CvDataTable.spec.js
Fix ci-check to prepare for building "next" package
=> chore: fix ci check for package build

.github/workflows/deploy-vue-storybook.yml, .github/workflows/release-vNext.yml, .github/workflows/stale.yml
Synch workflows from main to vNext
Make sure workflows can be run from vNext
=> chore: make sure all workflows are on the vNext branch

src/components/CvTextInput/CvTextInput.stories.js, src/components/CvTextInput/CvTextInput.vue, src/components/CvTextInput/__tests__/CvTextInput.spec.js, src/components/CvTextInput/const.js, src/components/CvTextInput/index.js
Contributes to #1437 
CvTextInput (and 'CvPasswordInput') implementation for vue3, following vue2 implementation and react-carbon v7 as base
Component features were added incrementally, per commit. Unit tests were added on each step
=> feat: cv text & password input - vue3

src/components/CvTextArea/CvTextArea.stories.js, src/components/CvTextArea/CvTextArea.vue, src/components/CvTextArea/__tests__/CvTextArea.spec.js, src/components/CvTextArea/index.js
Contributes to #1446 
CvTextArea implementation for vue3, following vue2 implementation and react-carbon v7 as base
Component features were added incrementally, per commit. Unit tests were added on each step
=> feat: cv text area - vue3

package.json, src/components/CvDatePicker/CvDatePicker-notes.md, src/components/CvDatePicker/CvDatePicker.stories.js, src/components/CvDatePicker/CvDatePicker.vue, src/components/CvDatePicker/CvDatePickerSkeleton.vue, src/components/CvDatePicker/__tests__/CvDatePicker.spec.js, src/components/CvDatePicker/index.js, src/components/CvDatePicker/plugins/appendToPlugin.js, src/components/CvDatePicker/plugins/fixEventsPlugin.js, src/components/CvDatePicker/plugins/monthSelectPlugin.js, src/components/CvDatePicker/plugins/rangePlugin.js, yarn.lock
Contributes to 
CvDatePicker implementation for Vue 3 using [@carbon/react@1.27.0](https://github.com/carbon-design-system/carbon/tree/main/packages/react) and [Carbon Components in Vue.js](https://github.com/carbon-design-system/carbon-components-vue/blob/main/packages/core/README.md) as reference
Using both unit tests and the stories
=> feat: implement CvDatePicker

src/components/CvModal/CvModal.stories.mdx, src/components/CvModal/CvModal.vue, src/components/CvModal/__tests__/CvModal.spec.js, src/components/CvModal/index.js
Contributes to #1454
Port cv-modal to Vue 3
Added to storybook and unit tests
=> feat: add cv-modal

.github/ISSUE_TEMPLATE/vue-3-porting.md
Tested in my own fork and works well.
The Vue 3 label is added automatically.
=> feat: Create vue 3 issue template

src/components/CvInlineLoading/CvInlineLoading.stories.mdx, src/components/CvInlineLoading/CvInlineLoading.vue, src/components/CvInlineLoading/__tests__/CvInlineLoading.spec.js, src/components/CvInlineLoading/consts.js, src/components/CvInlineLoading/index.js
=> feat: port inline loading to vue 3

src/components/CvAccordion/CvAccordion.stories.js, src/components/CvButton/CvButtonSkeleton.stories.js, src/components/CvCheckbox/__tests__/CvCheckbox.spec.js, src/components/CvDatePicker/CvDatePicker.vue, src/components/CvForm/CvFormGroup.vue, src/components/CvGrid/__tests__/CvGrid.spec.js, src/components/CvLoading/__tests__/CvLoading.spec.js, src/components/CvMultiSelect/__tests__/CvMultiSelect.spec.js, src/components/CvOverflowMenu/__tests__/CvOverflowMenu.spec.js, src/components/CvSelect/__tests__/CvSelect.spec.js, src/components/CvTabs/__tests__/CvTabs.spec.js, src/global/storybook-utils/story-source-code.js
Lint and test fix for Vue 3 build
=> fix: lint and failed tests

src/components/CvCheckbox/CvCheckbox.stories.js, src/components/CvCheckbox/CvCheckbox.vue, src/components/CvMultiSelect/CvMultiSelect.stories.mdx, src/use/cvCheck.js
The built version of the CvMultiSelect story is broken. This resolves it.
Built locally and viewed in local broswer.
=> fix: fix checkbox disabled attribute to solve CvMultiSelect story issue

.github/workflows/ci.yml, package.json
Set PR test to run on vNext branch
They were not running
Run the CI in my own repo
=> chore: vVext CI

.github/workflows/ci.yml
=> chore: add CI test for vNext PRs

src/components/CvSearch/CvSearch.stories.mdx, src/components/CvSearch/CvSearch.vue, src/components/CvSearch/__tests__/CvSearch.spec.js, src/components/CvSearch/index.js
Contributes to #1495
Port cv-search to Vue3
=> feat: cv search

src/components/CvFileUploader/CvFileUploader.stories.mdx, src/components/CvFileUploader/CvFileUploader.vue, src/components/CvFileUploader/CvFileUploaderItem.vue, src/components/CvFileUploader/CvFileUploaderSkeleton.vue, src/components/CvFileUploader/__tests__/CvFileUploader.spec.js, src/components/CvFileUploader/__tests__/CvFileUploaderItem.spec.js, src/components/CvFileUploader/const.js, src/components/CvFileUploader/index.js
Contributes to #1450
port cv-file-uploader to vue3.
I decided to leave part of the code a bit 'repeated/duplicated' to make it easier to reason. Is that's not ok, I can change it.
Deeply sorry for the long delay on this one. Had other things coming up these past few months. 
known issues:
- Adjust drag'n'drop area, that is clickable outside the area it supposed to
Mostly, unit tests missing are related to button kind & size and exposed methods
=> feat: cv-file-uploader

src/components/CvTooltip/index.js
Contributes to #591 and comment from #1498
export static values (original ones from Vue2 + additional enums for more convenient usage)
n/a
=> feat: cv-tooltip export static values

.github/workflows/release-republish.yml
Add a republish action
The last publish failed so this is a way to retry
=> chore: add republish action

src/components/CvDataTable/CvDataTable.stories.mdx, src/components/CvDataTable/CvDataTableHeading.vue
Contributes to #1560 
Added a sort function to the story and more documentation tot he story about the need for user's to implement their own search.
The current story emits the search events but does not actually sort the data. This is confusing.
=> fix: sort in datatable story.

.github/workflows/release-republish.yml, .github/workflows/release-v2.yml, .github/workflows/release-v3.yml
Hopefully resolve 2fa error in the npm publish
- Also tweaked the action file names for clarity
- Also updated the v2 publish a bit
=> chore: update npm references

README.md, SECURITY.md
These 2 files are blocking the ci check
=> chore: update md files to resolve ci check

src/components/CvDatePicker/CvDatePicker.stories.js, src/components/CvDatePicker/CvDatePicker.vue
Added additional story for the date picker component, which shows how to work with "minDate" and "maxDate" options.
Improved argTypes in the date picker story file.
Deleted unused prop "invalid" in the date picker component.
To improve component's appearance in the storybook.
With local story.
=> fix(cv-date-picker): improve date picker story

src/components/CvDataTable/CvDataTable.stories.mdx, src/components/CvDataTable/CvDataTable.vue, src/components/CvDataTable/_CvDataTableRowInner.vue, src/components/CvDataTable/cvDataTableStore.js, src/components/CvDropdown/CvDropdown.stories.mdx, src/components/CvDropdown/CvDropdown.vue, src/components/CvPagination/CvPagination.stories.mdx, src/components/CvPagination/CvPagination.vue
Update code based on slack channel questions
In storybook and in hello carbon vue3 app
=> fix: migration slack March 2024

package.json
=> fix: paths in test

README.md, telemetry.yml
This PR updates the endpoint within the package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.
Needed to update Telemetry endpoint URL for future data collection, as well as the wording of the README.
N/A
- [ X ] Yes
=> chore(telemetry): update endpoint and readme in v11 branch

package.json
Lint staged not linting all files
Noticed when testing #1660
=> fix: eslint not properly run by lint-staged

src/components/CvSvg/_CvSvg.vue, src/components/CvSvg/__tests__/CvSvg.spec.js, src/components/CvSvg/__tests__/__snapshots__/CvSvg.spec.js.snap
Fix CvSvg not rendering inline svg properly (#1724)
=> fix: for CvSvg, update props structure for Vue 3

.github/workflows/deploy-vue-storybook.yml
Upgrade workflow 'deploy-vue-storybook' to latest actions versions.
This workflow was using actions that are no longer supported, now using the latest versions so it should start working again
I did not... need to get it merged so we can check if it runs.
=> ci(storybook): upgrade deploy-vue-storybook to latest actions
