carbon-design-system/carbon-components-vue

.cfignore, .circleci/config.yml, .circleci/manifest.yml, .gitignore, Staticfile
Closes #45 
Adds in CI/CD process for deploying our storybook to IBM Cloud.
**New**
- Deployment-related files
**Changed**
- Add `storybook-static` to `.gitignore`
**Removed**
=> chore(deploy): add in steps to deploy storybook

README.md, package.json
Version initial set of components, based on v9 of carbon components, includes draft implementations of all non-data viz components in the core carbon components library. Public parts of the component: properties, events, data, methods, computed values are at this point subject to review.
=> chore(release): make version 0.1.0

src/components/cv-date-picker/cv-date-picker.vue, src/components/cv-number-input/cv-number-input.vue
Part of fix for issue #68 
**Changed**
- Adds \<div\>s with bx--form-item to the templates for cv-number-input and cv-date-picker, to match the Carbon components boilerplate.
=> fix: add div's with bx--form-item where missing

src/data-viz/cv-gauge/cv-gauge.vue
Closes #139
When amount or total props have been changed, reset svg
**New**
- nothing
**Changed**
- Visualisation method for the gauge arc in cv-gauge.vue
**Removed**
- nothing
=> fix: gauge component is not updated when change amount/total props

src/data-viz/cv-gauge/cv-gauge-story.js
Closes #141
Adjust notes for gauge component for storybook 4
**New**
- nothing
**Changed**
- cv-gauge-story.js
**Removed**
- nothing
=> fix: notes for gauge component are adjusted for storybook4

README.md, src/data-viz/cv-pie-chart/cv-pie-chart-notes.md, src/data-viz/cv-pie-chart/cv-pie-chart-story.js, src/data-viz/cv-pie-chart/cv-pie-chart.vue
Closes #52
Add pie char component. Props are dataArray, colors and header. Uses d3 library in the same way as in carbon vanilla implementation.
**New**
- data-viz/cv-pie-chart/cv-pie-chart-notes.md
- data-viz/cv-pie-chart/cv-pie-chart-story.js
- data-viz/cv-pie-chart/cv-pie-chart.vue
**Changed**
- status of CvPieChart in ReadMe
**Removed**
- nothing
=> feat(component): add pie chart component

src/data-viz/cv-bar-graph/cv-bar-graph-notes.md, src/data-viz/cv-bar-graph/cv-bar-graph-story.js, src/data-viz/cv-bar-graph/cv-bar-graph.vue
Closes #
Makes gridlines on the y-axis (dashed lines across the graph) optional via a property setting
**New**
- Makes gridlines on the y-axis optional via a property setting
=> feat: make y-axis gridlines optional

src/_storybook/views/sv-template-view/sv-template-view.vue, src/components/cv-text-area/cv-text-area-notes.md, src/components/cv-text-area/cv-text-area-story.js, src/components/cv-text-area/cv-text-area.vue, src/components/cv-text-input/cv-text-input-notes.md, src/components/cv-text-input/cv-text-input-story.js, src/components/cv-text-input/cv-text-input.vue
Closes #181 
Added using slops, a slot-prop hybrid in which the slot overrides the prop.
**Changed**
- CvTextArea
- CvTextInput
=> Add helper text and invalid

src/components/cv-number-input/cv-number-input.vue
Prevent number inputs within forms from prematurely submitting the form
Closes #
Same issue as [#1747](https://github.com/IBM/carbon-components/issues/1747) in IBM/carbon-components
**Changed**
- src/components/cv-number-input/cv-number-input.vue
=> fix(number input): add type=button to number input controls)

src/components/cv-overflow-menu/cv-overflow-menu.vue, src/components/cv-pagination/cv-pagination.vue, src/components/cv-slider/cv-slider.vue, src/components/cv-tooltip/cv-interactive-tooltip.vue
Closes #169 
Replace setTimeout with nextTick
**New**
-
**Changed**
- interactive-tooltip, slider, pagination and overflow-menu
**Removed**
-
**Comments**
Could you please check overflow-menu component? I am not 100% sure in the correctness of using nextTick for `focus` parts.
=> fix: nextTick instead of setTimeout

src/components/cv-tooltip/cv-tooltip-story.js
Closes #247 
Fix onclick actions for 'show tip' and 'hide tip' buttons for interactive tooltip storybook.
**Changed**
- storybook for interactive tooltip
=> fix: show tip and hide tip buttons for interactive tooltip storybook

src/components/cv-tile/_cv-tile-selectable.vue
The selectable tile was not correctly setting classes and other state attributes.
**Changed**
m  src/components/cv-tile/_cv-tile-selectable.vue
=> fix: selectable tile state

packages/core/package.json, packages/core/src/components/cv-search/cv-search-notes.md, packages/core/src/components/cv-search/cv-search.vue, packages/data-viz/package.json, storybook/package.json, storybook/stories/cv-search-story.js
Closes #314
Change search sizing to use a small property in line with the design language page.
M       packages/core/src/components/cv-search/cv-search-notes.md
M       packages/core/src/components/cv-search/cv-search.vue
M       storybook/stories/cv-search-story.js
=> Search fix

packages/core/src/components/cv-structured-list/_cv-structured-list-item-selectable.vue, packages/core/src/components/cv-structured-list/cv-structured-list.vue
Fix linter warnings in structured list
M       packages/core/src/components/cv-structured-list/_cv-structured-list-item-selectable.vue
M       packages/core/src/components/cv-structured-list/cv-structured-list.vue
=> fix: linter warnings in structures list

packages/core/src/components/cv-data-table/cv-data-table.vue
This fixes size, zebra, and borderless props.
**Changed**
- Fixes modifier class prefixes in cv-data-table
=> Flip modifier prefix for componentsX

packages/core/src/components/cv-tile/_cv-tile-expandable.vue
Closes #369 
Make expandable tile expand on tile click instead of just chevron.
M       packages/core/src/components/cv-tile/_cv-tile-expandable.vue
=> fix: expand tile updates

packages/core/src/components/cv-text-area/cv-text-area.vue, packages/core/src/components/cv-text-input/cv-text-input.vue
Closes #368
Correct styling of text input when disabled or invalid.
M       packages/core/src/components/cv-text-area/cv-text-area.vue
=> fix: disabled invalid styling

packages/core/src/components/cv-tabs/cv-tab.vue
Closes #
Correct name of cv tab component
=> fix: cv-tab name

packages/core/src/components/cv-data-table/cv-data-table.vue
Respect `item.label` when assembling `dataColumns`
**Changed**
- Data Table: Respect `item.label` when assembling `dataColumns`
=> Respect item.label when assembling dataColumns

packages/core/src/components/cv-pagination/cv-pagination.vue
When `numberOfItems` changes (e.g. is loaded from a remote source and available after `mounted`), this preserves the current page (or drops it to the last available page) instead of jumping to the last page.
**Changed**
- Pagination: preserves current page when `numberOfItems` changes
=> Pagination fixes

packages/core/src/components/cv-data-table/cv-data-table.vue
This enables searching when `@search` is present but no `actions` slot is provided.
**Changed**
- Enables searching when no `actions` slot is provided
=> Enable searching without providing an actions slot

packages/core/package.json, packages/core/src/components/cv-structured-list/cv-structured-list-notes.md, packages/core/src/components/cv-structured-list/cv-structured-list.vue, storybook/package.json, storybook/stories/cv-structured-list-story.js
Closes #364
Removes border option from the structured list
m  packages/core/src/components/cv-structured-list/cv-structured-list-notes.md
m  packages/core/src/components/cv-structured-list/cv-structured-list.vue
m  storybook/stories/cv-structured-list-story.js
=> Tidy structured list

packages/core/src/components/cv-ui-shell/_cv-side-nav-footer.vue, packages/core/src/components/cv-ui-shell/_cv-side-nav-link-text.vue, packages/core/src/components/cv-ui-shell/cv-header-menu-button.vue, packages/core/src/components/cv-ui-shell/cv-header-menu.vue, packages/core/src/components/cv-ui-shell/cv-header.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-icon.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-items.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu-item.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue, packages/core/src/components/cv-ui-shell/cv-switcher-item-link.vue, storybook/_storybook/views/sv-template-view/sv-template-view.vue, storybook/stories/cv-ui-shell-story.js
Part of #353 
A first pass at the left panel leaving the UI Shell in a similar position to Carbon React 10.3.0
A       packages/core/src/components/cv-ui-shell/_cv-side-nav-footer.vue
A       packages/core/src/components/cv-ui-shell/_cv-side-nav-link-text.vue
R076    packages/core/src/components/cv-ui-shell/cv-button-menu.vue     packages/core/src/components/cv-ui-shell/cv-header-menu-button.vue
M       packages/core/src/components/cv-ui-shell/cv-header-menu.vue
M       packages/core/src/components/cv-ui-shell/cv-header-panel.vue
M       packages/core/src/components/cv-ui-shell/cv-header.vue
A       packages/core/src/components/cv-ui-shell/cv-side-nav-icon.vue
A       packages/core/src/components/cv-ui-shell/cv-side-nav-items.vue
A …
=> feat: add side nav

packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue
Fixes side panel and header panel issue where focus was not getting to interactive content on the panel.
Changed:
M       packages/core/src/components/cv-ui-shell/cv-header-panel.vue
M       packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue
M       packages/core/src/components/cv-ui-shell/cv-side-nav.vue
=> fix: focus not showing on panel links

packages/core/src/components/cv-ui-shell/cv-side-nav-items.vue
Corrects side nav focus
1. Open http://vue.carbondesignsystem.com/?path=/story/experimental-cvuishell-header--header-base-with-side-nav
2. If hamburger not shown reduce width until visible.
3. Click on hamburger to show side nav
4. Click on background of side nav, hamburger will lose focus.
5. Move mouse out of side nav, it should not close.
Changelog
M       packages/core/src/components/cv-ui-shell/cv-side-nav-items.vue
=> fix: side nave focus

packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue
Closes #457
Sidenav sub menu was auto closing on focusout, removed this behaviour.
Also added temporary CSS fix for https://github.com/carbon-design-system/carbon/issues/2928
=> fix: remove auto closing in sidenav menu

packages/core/src/components/cv-radio-button/cv-radio-button.vue, packages/core/src/components/cv-radio-button/cv-radio-group.vue, storybook/stories/cv-radio-button-story.js
Closes #481 
Add vertical radio group and left label options.
M       packages/core/src/components/cv-radio-button/cv-radio-button.vue
M       packages/core/src/components/cv-radio-button/cv-radio-group.vue
M       storybook/stories/cv-radio-button-story.js
=> Feat update radio group

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, storybook/stories/cv-multi-select-story.js
Closes #501
The following is true for combobox and multi-select
- Removes space auto-completion to allow spaces in filter.
- Enter now used for auto-completion
- Escapes regex special characters
M       storybook/stories/cv-multi-select-story.js
=> fix: combobox behaviour

packages/core/package.json, packages/core/src/components/cv-link/cv-link.vue, packages/core/src/mixins/link-mixin.js, storybook/package.json
Closes #506
Change how href and to are applied to <a /> and <router-link />
M       packages/core/src/components/cv-link/cv-link.vue
M       packages/core/src/mixins/link-mixin.js
=> Cv link issue506

packages/core/CHANGELOG.md, packages/core/src/components/cv-tile/_cv-tile-clickable.vue, packages/core/src/components/cv-ui-shell/cv-header-menu-item.vue, packages/core/src/components/cv-ui-shell/cv-header-name.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu-item.vue, packages/core/src/components/cv-ui-shell/cv-skip-to-content.vue, packages/core/src/components/cv-ui-shell/cv-switcher-item-link.vue
part of #506
Update other link mixin usage to match cv-link
M       packages/core/src/components/cv-tile/_cv-tile-clickable.vue
M       packages/core/src/components/cv-ui-shell/cv-header-menu-item.vue
M       packages/core/src/components/cv-ui-shell/cv-header-name.vue
M       packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue
M       packages/core/src/components/cv-ui-shell/cv-side-nav-menu-item.vue
M       packages/core/src/components/cv-ui-shell/cv-skip-to-content.vue
M       packages/core/src/components/cv-ui-shell/cv-switcher-item-link.vue
=> fix: update link-mixin usage in all components

packages/core/src/components/cv-ui-shell/cv-header-menu.vue, storybook/stories/cv-ui-shell-story.js
Closes #510 
Add title to header menu.
m packages/core/src/components/cv-ui-shell/cv-header-menu.vue
m storybook/stories/cv-ui-shell-story.js
=> fix: add missing menu title

packages/core/src/components/cv-code-snippet/cv-code-snippet.vue
Closes #522
Copies the innerText as opposed to the innerHTML of the code snippet to the clipboard.
- m packages/core/src/components/cv-code-snippet/cv-code-snippet.vue
=> fix: code snippet copy

packages/core/src/components/cv-progress/cv-progress-notes.md, packages/core/src/components/cv-progress/cv-progress-step.vue, packages/core/src/components/cv-progress/cv-progress.vue, storybook/stories/cv-progress-story.js
Adds a vertical progress option and enhances the tooltip so it is shown only if explicitly provided or the label is truncated.
M       packages/core/src/components/cv-progress/cv-progress-notes.md
M       packages/core/src/components/cv-progress/cv-progress-step.vue
M       packages/core/src/components/cv-progress/cv-progress.vue
M       storybook/stories/cv-progress-story.js
=> feat: vertical progress and tip enhancement

packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-action.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-text-input/cv-text-input.vue
Closes #536 
Set button type="button" for buttons that are not cv-buttons
M       packages/core/src/components/cv-data-table/cv-data-table-action.vue
=> fix: correct non-cv-button button types

packages/core/package.json, packages/core/src/components/cv-text-input/cv-text-input-notes.md, packages/core/src/components/cv-text-input/cv-text-input.vue, storybook/package.json, storybook/stories/cv-text-input-story.js
Closes  #541 
Add passwordHideLabel and passwordShowLabel to the text input box for use on the hide/show password icon
M       packages/core/src/components/cv-text-input/cv-text-input-notes.md
M       storybook/stories/cv-text-input-story.js
=> Password button labels

packages/core/package.json, packages/core/src/components/cv-modal/cv-modal.vue, storybook/package.json, storybook/stories/cv-modal-story.js
Adds modal hide request event when auto-hide-off attribute used. This transfers responsibility for closing the modal to the component user.
M       storybook/stories/cv-modal-story.js
=> Modal hide request

packages/core/package.json, packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, storybook/package.json
Perhaps fix #542
When an overflow menu closes stop it grabbing focus
=> Overflow focus issue

packages/core/src/components/cv-code-snippet/_cv-code-snippet-inline.vue, packages/core/src/components/cv-code-snippet/_cv-code-snippet-multiline.vue, packages/core/src/components/cv-code-snippet/_cv-code-snippet-oneline.vue, packages/core/src/components/cv-code-snippet/cv-code-snippet-notes.md, packages/core/src/components/cv-code-snippet/cv-code-snippet.vue, storybook/stories/cv-code-snippet-story.js
Closes #345
Adds theme 'light' to inline code snippet. 
Also adds options for the feedback button to change it's aria-label and the feedback message.
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-inline.vue
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-multiline.vue
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-oneline.vue
M       packages/core/src/components/cv-code-snippet/cv-code-snippet-notes.md
M       packages/core/src/components/cv-code-snippet/cv-code-snippet.vue
M       storybook/stories/cv-code-snippet-story.js
=> feat: add code snippet theme for inline

packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue
Closes #557
Overflow and interactive tooltip popups are moved out to the body so they appear above other content. This fix puts them back before the component is destroyed.
M       packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue
=> fix: popup proliferation on render

packages/core/src/components/cv-button/button-mixin.js, packages/core/src/components/cv-button/cv-button-notes.md, packages/core/src/components/cv-button/cv-button-skeleton.vue, packages/core/src/components/cv-button/cv-button.vue, packages/core/src/components/cv-button/cv-icon-button.vue, packages/core/src/components/cv-button/index.js, packages/core/src/index.js, storybook/_storybook/utils/knobs-helper.js, storybook/stories/cv-button-story.js
Adds an icon button and other changes to reflect Carbon 10.6
A       packages/core/src/components/cv-button/button-mixin.js
M       packages/core/src/components/cv-button/cv-button-notes.md
M       packages/core/src/components/cv-button/cv-button-skeleton.vue
A       packages/core/src/components/cv-button/cv-icon-button.vue
M       packages/core/src/components/cv-button/index.js
M       packages/core/src/index.js
M       storybook/_storybook/utils/knobs-helper.js
M       storybook/stories/cv-button-story.js
=> Carbon10 6 updates

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Closes #584 
Fixes the arrow icon being replaced by the `internalValue` when set (`this.$refs.valueContent.innerHTML = child.internalContent;`) by changing the `valueContent` to the span where the text should be rather than the parent of the span and the icon.
`M       packages/core/src/components/cv-dropdown/cv-dropdown.vue`
=> fix(cv dropdown): inline dropdown arrow icon missing

packages/core/src/components/cv-dropdown/cv-dropdown-item.vue, packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/stories/cv-tabs-story.js
Closes #599
There was a couple of typos in cv:beforeDestroy event names and also in how swapping out a data set was handled to ensure an item is selected.
M       packages/core/src/components/cv-dropdown/cv-dropdown-item.vue
=> Cv tabs from data fix

packages/core/__tests__/cv-breadcrumb.test.js
#182 
Add tests for CvBreadcrumb
A       packages/core/__tests__/cv-breadcrumb.test.js
I could not test CvBreadcrumbItemSkeleton component probably because it starts with `_`.
=> feat: add tests for breadcrumb component

packages/core/src/components/cv-button/cv-icon-button.vue, packages/core/src/components/cv-overflow-menu/cv-overflow-menu-notes.md, packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, storybook/stories/cv-button-story.js, storybook/stories/cv-overflow-menu-story.js
Updates the overflow menu to 10 7 stylings and accessibility
M       packages/core/src/components/cv-overflow-menu/cv-overflow-menu-notes.md
M       storybook/stories/cv-button-story.js
M       storybook/stories/cv-overflow-menu-story.js
=> feat: update overflow to 10 7

packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-tabs/cv-tabs.vue
An experiment for #671
- Change so that events are not raised if the same tab is selected again. 
- Change behaviour on tab mount to only check tab selection if none selected.
- Change behaviour on tab destroy to only check tab selection if selected or left of removed.
=> fix: test update for cv-tabs

packages/core/src/components/cv-inline-notification/cv-inline-notification.vue
Closes #622
Remove extra dot in the sub-title of CvInlineNotification
M       packages/core/src/components/cv-inline-notification/cv-inline-notification.vue
=> fix: remove extra dot from subtitle

packages/core/src/components/cv-tooltip/cv-definition-tooltip.vue, packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue, packages/core/src/components/cv-tooltip/cv-tooltip-notes.md, packages/core/src/components/cv-tooltip/cv-tooltip.vue, storybook/stories/cv-tooltip-story.js
Part of #581
Update CvTooltip and variants formats to 10-7 button version
M       packages/core/src/components/cv-tooltip/cv-definition-tooltip.vue
M       packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue
M       packages/core/src/components/cv-tooltip/cv-tooltip-notes.md
M       packages/core/src/components/cv-tooltip/cv-tooltip.vue
M       storybook/stories/cv-tooltip-story.js
=> chore: update tooltip to 10-7 form

packages/core/src/components/cv-data-table/cv-data-table.vue
Closes #615 
Remove use of trimRight for IE11  support.
m  packages/core/src/components/cv-data-table/cv-data-table.vue
=> fix: replace trimright with trim for wider support

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/cv-number-input/cv-number-input-notes.md, packages/core/src/components/cv-number-input/cv-number-input.vue, storybook/package.json, storybook/stories/cv-number-input-story.js
Closes #630
Allow the number input to work with number and string values.
M       packages/core/src/components/cv-number-input/cv-number-input-notes.md
M       storybook/stories/cv-number-input-story.js
=> Allow the number input to work with number and string values

packages/core/__tests__/__snapshots__/cv-tag.test.js.snap, packages/core/__tests__/cv-toggle.test.js
Corrects CvToggle tests broken by 10-7 update
M       packages/core/__tests__/__snapshots__/cv-tag.test.js.snap
M       packages/core/__tests__/cv-toggle.test.js
=> fix: toggle tests broken by 10-7 update

packages/core/src/components/cv-button/cv-icon-button.vue, packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, packages/core/src/components/cv-tooltip/cv-definition-tooltip.vue, packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue, packages/core/src/components/cv-tooltip/cv-tooltip.vue
Fixes use of role button which should have been type button.
M       packages/core/src/components/cv-tooltip/cv-definition-tooltip.vue
M       packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue
M       packages/core/src/components/cv-tooltip/cv-tooltip.vue
=> fix: role button usage when type was intended

packages/core/__tests__/_helpers.js
Fix prop type test which was failing when the property declaration was not the object form.
m packages/core/__tests__/_helpers.js
=> fix: prop type test in case of plain prop

packages/core/__tests__/__snapshots__/cv-breadcrumb.test.js.snap, packages/core/__tests__/cv-breadcrumb.test.js
Change breadcrumb tests to use snapshots for render checks.
A       packages/core/__tests__/__snapshots__/cv-breadcrumb.test.js.snap
M       packages/core/__tests__/cv-breadcrumb.test.js
=> chore: breadcrumb test snapshots for render

packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap, packages/core/__tests__/_helpers.js, packages/core/__tests__/cv-number-input.test.js, packages/core/src/components/cv-number-input/cv-number-input.vue
#182 
Add tests for CvNumberInput. Added default value for `label` prop for CvNumberInput component.
A       packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap
M       packages/core/__tests__/_helpers.js
A       packages/core/__tests__/cv-number-input.test.js
I am not sure I implemented the snapshot tests correctly.
Test Coverage:
=> feat: add tests for cvnumberinput

packages/core/__tests__/__snapshots__/cv-button.test.js.snap, packages/core/__tests__/cv-button.test.js, packages/core/src/components/cv-button/button-mixin.js, packages/core/src/components/cv-button/cv-button-skeleton.vue, packages/core/src/components/cv-button/cv-button.vue, packages/core/src/components/cv-button/cv-icon-button.vue
Closes #644 
In adding tests to CvButton the use of @click alongside $listeners caused two events in the button. This had consequences wherever a button is used. Switched to using a computed listeners value as per https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model
A       packages/core/__tests__/__snapshots__/cv-button.test.js.snap
M       packages/core/__tests__/cv-button.test.js
M       packages/core/src/components/cv-button/button-mixin.js
M       packages/core/src/components/cv-button/cv-button-skeleton.vue
=> Button press twice fix

packages/core/__tests__/__snapshots__/cv-checkbox.test.js.snap, packages/core/__tests__/_helpers.js, packages/core/__tests__/cv-button.test.js, packages/core/__tests__/cv-checkbox.test.js, packages/core/__tests__/cv-number-input.test.js, packages/core/__tests__/cv-wrapper.test.js
Update checkbox to use snapshot tests
A       packages/core/__tests__/__snapshots__/cv-checkbox.test.js.snap
M       packages/core/__tests__/_helpers.js
M       packages/core/__tests__/cv-button.test.js
M       packages/core/__tests__/cv-checkbox.test.js
M       packages/core/__tests__/cv-number-input.test.js
M       packages/core/__tests__/cv-wrapper.test.js
=> chore: update checkbox tests to use snapshots

packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue
Closes #655 
DOM Change in 2.16 for carbon 10.7 invalidated one of the focus checks
=> fix: overflow menu close on button click

packages/core/__tests__/__snapshots__/cv-radio-button.test.js.snap, packages/core/__tests__/_helpers.js, packages/core/__tests__/cv-radio-button.test.js
#182 
Added tests for CvRadioButton and CvRadioGroup. Did not know to to test events for these components.
A       packages/core/__tests__/__snapshots__/cv-radio-button.test.js.snap
M       packages/core/__tests__/_helpers.js
A       packages/core/__tests__/cv-radio-button.test.js
=> feat: add tests for radio button

packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, packages/core/src/components/cv-tag/cv-tag.vue
Closes #553
Prevents dropdowns being used when disabled
M       packages/core/src/components/cv-tag/cv-tag.vue
=> fix: dropdowns working when disabled

packages/core/src/components/cv-tabs/cv-tabs.vue
Closes #664 
Early exit clause from loop was preventing lower tabs from being hidden.
m packages/core/src/components/cv-tabs/cv-tabs.vue
=> fix: lower index tabs not closing

packages/core/src/components/cv-tabs/cv-tabs.vue, storybook/stories/cv-tabs-story.js
The current implementation of CvTabs tries to use a CvDropdown which means the DOM is not similar to that used by core carbon. This PR chagnes it to use the same DOM.
=> feat: switch tabs to use standard carbon html

packages/core/__tests__/__snapshots__/cv-link.test.js.snap, packages/core/__tests__/cv-link.test.js
#182 
Add tests for CvLink component.
Could not get rid of the following warning when `router-link` is used:
> [Vue warn]: Unknown custom element: <router-link> - did you register the component correctly?
I true to use `localVue` and `stubs` as described here https://vue-test-utils.vuejs.org/guides/using-with-vue-router.html, but it did not help.
A       packages/core/__tests__/__snapshots__/cv-link.test.js.snap
A       packages/core/__tests__/cv-link.test.js
=> feat: add tests for CvLink

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-action.vue, packages/core/src/components/cv-data-table/cv-data-table-row.vue, packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-date-picker/cv-date-picker.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-modal/cv-modal.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, packages/core/src/components/cv-number-input/cv-number-input.vue, packages/core/src/components/cv-select/cv-select.vue, packages/core/src/components/cv-text-area/cv-text-area.vue, packages/core/src/components/cv-text-input/cv-text-input.vue, packages/core/src/components/cv-time-picker/cv-time-picker.vue, packages/core/src/components/cv-ui-shell/cv-header.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue, storybook/_storybook/utils/knobs-helper.js, storybook/_storybook/views/sv-template-view/sv-template-view.vue, storybook/stories/cv-combo-box-story.js, storybook/stories/cv-date-picker-story.js, storybook/stories/cv-dropdown-story.js, storybook/stories/cv-multi-select-story.js, storybook/stories/cv-select-story.js, storybook/stories/cv-time-picker-story.js
Closes #671
An assumption made about $slots and reactivity was causing the invalid-message slot to persist the invalid state of a component. The components now check during component update for the slots existence.
M       packages/core/src/components/cv-data-table/cv-data-table-action.vue
M       packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue
M …
=> fix: slot hide show reactivity

packages/core/src/components/cv-combo-box/cv-combo-box.vue
Closes #679 
Sets the `placeholder` prop of in `input` element to the `{{label}}` vue prop
`M       packages/core/src/components/cv-combo-box/cv-combo-box.vue`
=> fix: CvComboBox set input placeholder to label

packages/core/src/components/cv-combo-box/cv-combo-box.vue
Closes #684 
The v-model was not updating when the clear icon button was clicked, this PR edits the method of that button `clearFilter()` to update the internal value to an empty string `''` (which will update `this.dataValue`), and then emit this change.
`M       packages/core/src/components/cv-combo-box/cv-combo-box.vue`
=> fix: update and emit dataValue on clearFilter

packages/core/__tests__/__snapshots__/cv-text-area.test.js.snap, packages/core/__tests__/cv-text-area.test.js, packages/core/src/components/cv-text-area/cv-text-area.vue
#182
Add tests for CvTextArea component. Noticed, that isInvalid and isHelper computed values return Number, not Boolean - changed that.
A       packages/core/__tests__/__snapshots__/cv-text-area.test.js.snap
A       packages/core/__tests__/cv-text-area.test.js
M       packages/core/src/components/cv-text-area/cv-text-area.vue
=> feat: add tests for cv-text-area component|

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue
Closes #681 #677
Combo box was attempting to apply a null filter causing an error if 'auto-filter' was true on mounted. Now ignores falsy filter strings on mounted.
Multi select in filter mode was placing focus in the input causing it to re-open.
=> fix: combobox and multi select issues

packages/core/src/components/cv-overflow-menu/cv-overflow-menu-item.vue
Updated overflow menu html to include bx--overflow-menu-options__option-content which was missing
M       packages/core/src/components/cv-overflow-menu/cv-overflow-menu-item.vue
=> fix: correct overflow menu dom

packages/core/src/components/cv-multi-select/cv-multi-select.vue
Closes #699 
Makes the input's placeholder use the `label` prop
M packages/core/src/components/cv-multi-select/cv-multi-select.vue
=> fix: cvmultiselect label not used when filterable is true

packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap, packages/core/__tests__/cv-number-input.test.js
#182
Noticed that slots were not used correctly in snapshot tests for CvNumberInput. Also I think isInvalid should return Boolean (I did not change that).
M       packages/core/__tests__/__snapshots__/cv-number-input.test.js.snap
M       packages/core/__tests__/cv-number-input.test.js
=> fix: snapshot test for cv-number-input with slots

packages/core/src/components/cv-button/cv-icon-button.vue
Closes #703
The CvIcon property tipText was being used in render when it should have been using label.
m packages/core/src/components/cv-button/cv-icon-button.vue
=> fix: CvIconButton tooltip

packages/core/__tests__/__snapshots__/cv-button.test.js.snap, packages/core/__tests__/cv-accordion.test.js, packages/core/__tests__/cv-breadcrumb.test.js, packages/core/__tests__/cv-button.test.js, packages/core/__tests__/cv-checkbox.test.js, packages/core/__tests__/cv-tabs.test.js, packages/core/__tests__/cv-tag.test.js, packages/core/__tests__/cv-toggle.test.js, packages/core/__tests__/cv-wrapper.test.js, packages/core/src/components/cv-button/cv-button-skeleton.vue, packages/core/src/components/cv-button/cv-button.vue, packages/core/src/components/cv-button/cv-icon-button.vue, packages/core/src/mixins/carbon-prefix-mixin.js
Straw man bx prefix for CvButton
M       packages/core/__tests__/__snapshots__/cv-button.test.js.snap
M       packages/core/__tests__/cv-accordion.test.js
M       packages/core/__tests__/cv-breadcrumb.test.js
M       packages/core/__tests__/cv-button.test.js
M       packages/core/__tests__/cv-checkbox.test.js
M       packages/core/__tests__/cv-tabs.test.js
M       packages/core/__tests__/cv-tag.test.js
M       packages/core/__tests__/cv-toggle.test.js
M       packages/core/__tests__/cv-wrapper.test.js
M       packages/core/src/components/cv-button/cv-button-skeleton.vue
A       packages/core/src/mixins/carbon-prefix-mixin.js
=> Css prefix

packages/core/src/components/cv-inline-loading/consts.js, packages/core/src/components/cv-inline-loading/cv-inline-loading-notes.md, packages/core/src/components/cv-inline-loading/cv-inline-loading.vue, storybook/stories/cv-inline-loading-story.js
Adds ending state to inline loading component
M       packages/core/src/components/cv-inline-loading/consts.js
M       packages/core/src/components/cv-inline-loading/cv-inline-loading-notes.md
M       packages/core/src/components/cv-inline-loading/cv-inline-loading.vue
M       storybook/stories/cv-inline-loading-story.js
=> feat: add ending state to inline loading

packages/core/__tests__/__snapshots__/cv-inline-loading.test.js.snap, packages/core/__tests__/cv-inline-loading.test.js, packages/core/src/components/cv-inline-loading/cv-inline-loading.vue
#182
Add tests for CvInlineLoading component. I changed one output inside a prop validator to make the error message more informative:
From:
To: 
A       packages/core/__tests__/__snapshots__/cv-inline-loading.test.js.snap
A       packages/core/__tests__/cv-inline-loading.test.js
M       packages/core/src/components/cv-inline-loading/cv-inline-loading.vue
=> feat: add tests for cv-inline-loading

packages/core/__tests__/__snapshots__/cv-toast-notification.test.js.snap, packages/core/__tests__/cv-toast-notification.test.js, packages/core/src/components/cv-toast-notification/cv-toast-notification.vue
#182 
Add tests for CvToastNotification component. I changed small part in the component to get rid of this error when I was using 'info' toast notification:
A       packages/core/__tests__/__snapshots__/cv-toast-notification.test.js.snap
A       packages/core/__tests__/cv-toast-notification.test.js
M       packages/core/src/components/cv-toast-notification/cv-toast-notification.vue
=> test: add tests for cv-toast-notification

.gitignore, storybook/.storybook/webpack.config.js, storybook/_storybook/views/sv-template-view/sv-welcome.vue, storybook/package.json
Closes #712
parse package info more robustly, and cope with error logs in it
**NB** anyone with an existing clone of carbon-components-vue that they have built at least once will find an untracked file 'package-info.json' shows up when they pull this change in -- it should simply be deleted.
M       .gitignore
M       storybook/.storybook/webpack.config.js
M       storybook/_storybook/views/sv-template-view/sv-welcome.vue
=> fix: ensure build can complete without network

packages/core/__tests__/__snapshots__/cv-inline-notification.test.js.snap, packages/core/__tests__/cv-inline-notification.test.js, packages/core/src/components/cv-inline-notification/cv-inline-notification.vue
#182
Tests for `CvInlineNotification`. I am having a problem with testing computed `icon` value. It should be the same as for `CvToastNotification`, but it fails with the error and I have no idea why. The test is commented.
A       packages/core/__tests__/__snapshots__/cv-inline-notification.test.js.snap
A       packages/core/__tests__/cv-inline-notification.test.js
M       packages/core/src/components/cv-inline-notification/cv-inline-notification.vue
=> test: add tests for cv-inline-notification

packages/core/__tests__/__snapshots__/cv-toast-notification.test.js.snap, packages/core/__tests__/cv-toast-notification.test.js, packages/core/src/components/cv-toast-notification/cv-toast-notification.vue
According to carbon design website (https://www.carbondesignsystem.com/components/notification/code), warning toast notification uses warning--filled/20 icon instead of warning--alt--filled/20.
M       packages/core/__tests__/__snapshots__/cv-toast-notification.test.js.snap
M       packages/core/__tests__/cv-toast-notification.test.js
M       packages/core/src/components/cv-toast-notification/cv-toast-notification.vue
=> fix: use warning--filled/20 icon for warning toast notification

packages/core/__tests__/cv-link.test.js, packages/core/src/mixins/link-mixin.js
Closes #738
Allow an object to be passed to the 'to' property of the cv-link
M       packages/core/__tests__/cv-link.test.js
M       packages/core/src/mixins/link-mixin.js
=> feat: support Location for router-link

packages/core/src/components/cv-data-table/cv-data-table.vue
Closes #749
Fix `required` property typo in `CvDataTable` component
The git diff returns nothing, this is the commit info:
```
commit 4f25b400ae2ff627084ceb68f6e6e50f3a8ed63f (HEAD -> master, origin/master, origin/HEAD)
```
=> Fix typo in property declaration

packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-date-picker/cv-date-picker.vue
Closes #762
Fix `dataValue` property reference which was causing a runtime error while trying to access `endDate` value while on range mode of the `CvDatePicker` component.
M packages/core/src/components/cv-date-picker/cv-date-picker.vue
=> Fix property name causing reference issue

packages/core/src/components/cv-number-input/cv-number-input.vue, storybook/stories/cv-number-input-story.js
Fixes a problem when using a number type for value and a step of 0.01 with v-model or bound value. In this case if the user tried typed to reduce the number of decimal places below 2 the component would add the decimal places back in and place the cursor after the last 0.
Updated storybook so step knob works with v-model
M       storybook/stories/cv-number-input-story.js
=> Number input decimal input

packages/core/__tests__/cv-number-input.test.js, packages/core/src/components/cv-number-input/cv-number-input.vue
Correct type emitted from CvNumberInput when value is string
M       packages/core/__tests__/cv-number-input.test.js
=> Number input test upd

packages/core/__tests__/__snapshots__/cv-inline-loading.test.js.snap, packages/core/src/components/cv-inline-loading/cv-inline-loading.vue
This PR brings over the icon change in the InlineLoading component from the react package: https://github.com/carbon-design-system/carbon/pull/5018
```
M       packages/core/__tests__/__snapshots__/cv-inline-loading.test.js.snap
M       packages/core/src/components/cv-inline-loading/cv-inline-loading.vue
```
=> fix(inline-loading): change Error20 icon to ErrorFilled16

packages/core/src/components/cv-toast-notification/cv-toast-notification-notes.md
Fix title from `cv-toogle` to `cv-toast-notification`
No need to, I believe 😅
=> Update cv-toast-notification-notes.md to fix title

storybook/_storybook/views/sv-template-view/sv-template-view.vue
Closes #801
Correct story copy button position.
m storybook/_storybook/views/sv-template-view/sv-template-view.vue
=> fix: story copy button position

packages/core/src/components/cv-modal/cv-modal-notes.md, packages/core/src/components/cv-modal/cv-modal.vue, storybook/stories/cv-modal-story.js
Closes #812
Add closeAriaLabel property to modal dialog.
m packages/core/src/components/cv-modal/cv-modal-notes.md
m packages/core/src/components/cv-modal/cv-modal.vue
m storybook/stories/cv-modal-story.js
=> fix: add close aria label to modal

packages/core/src/components/cv-button/button-mixin.js, packages/core/src/components/cv-button/cv-button-skeleton.vue, packages/core/src/components/cv-button/cv-button.vue, packages/core/src/components/cv-button/cv-icon-button.vue
Closes #817
Makes the small property value undefined by default stopping the deprecation message appear when not small was not supplied.
=> fix: correct button small deprecation behaviour

packages/core/src/components/cv-pagination/cv-pagination.vue, packages/core/src/components/cv-time-picker/cv-time-picker.vue
Closes #821 #720
Use change event where CvSelect is used internally to support IE11. Pagination and  time picker are affected.
m packages/core/src/components/cv-pagination/cv-pagination.vue 
m packages/core/src/components/cv-time-picker/cv-time-picker.vue
=> Cv input use fix

packages/core/__tests__/cv-inline-loading.test.js, packages/core/src/components/cv-inline-loading/cv-inline-loading.vue
Closes #807
Allow case insensitiviy on inline loading states
m packages/core/__tests__/cv-inline-loading.test.js 
m packages/core/src/components/cv-inline-loading/cv-inline-loading.vue
=> fix: lower case loading states

packages/core/src/components/cv-data-table/cv-data-table.vue
Closes #825 
Correct column styling for headers and data when using sorted columns.
m packages/core/src/components/cv-data-table/cv-data-table.vue
=> fix: heading and data style when sortable

packages/core/src/components/cv-data-table/_cv-data-table-heading.vue, packages/core/src/components/cv-data-table/cv-data-table.vue
Closes #825 
When sortable styling the th was not effective. Moved the styles down to the contained elements.
M       packages/core/src/components/cv-data-table/_cv-data-table-heading.vue
=> fix: column styles on chrome

packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue
Add id attribute to panels controlled by header buttons
m  packages/core/src/components/cv-ui-shell/cv-header-panel.vue 
m  packages/core/src/components/cv-ui-shell/cv-side-nav.vue
=> fix: ids for controlled panels

packages/core/src/components/cv-code-snippet/_cv-code-snippet-multiline.vue, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, storybook/stories/cv-data-table-story.js
Closes #832
Add aria-label-for-batch-checkbox property to row and default
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-multiline.vue
=> fix: missing aria label on batch action checkbox

packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue
Closes #833 
cv-overflow-menu issue in IE.
packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue
=> Issue#833 - Overflow Menu fix for IE browsers

packages/core/__tests__/__snapshots__/cv-checkbox.test.js.snap, packages/core/src/components/cv-checkbox/cv-checkbox-notes.md, packages/core/src/components/cv-checkbox/cv-checkbox.vue, storybook/stories/cv-checkbox-story.js
Closes #835
Adds hide-label attribute to checkbox
M       packages/core/__tests__/__snapshots__/cv-checkbox.test.js.snap
M       packages/core/src/components/cv-checkbox/cv-checkbox-notes.md
M       packages/core/src/components/cv-checkbox/cv-checkbox.vue
M       storybook/stories/cv-checkbox-story.js
=> feat: add hide label to checkbox

packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue
Closes #849
Add role="tab" attribute to content switcher buttons to allow aria-selected
m. packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue
=> fix: content switcher accessibility

packages/core/src/components/cv-content-switcher/cv-content-switcher.vue
Closes #849
Additional update to add tablist to CvContnetSwitcher
m.  packages/core/src/components/cv-content-switcher/cv-content-switcher.vue
=> fix: add role tablist to CvContentSwitcher

packages/core/src/components/cv-tooltip/cv-tooltip.vue
Closes #862
Accordingly to [this doc](https://vue.carbondesignsystem.com/?path=/info/components-cvtooltip--default-interactive-tootlip), the `direction` property can be configured with the values `'top', 'left', 'right', 'bottom'`.
The tooltip component currently accepts `top` and `bottom` as valid options in its validation logic, but if you do use `left` and `right` you get an error and the expected behavior IS applied.
Add `left` and `right` options into the validator logic
=> Add `left` and `right` as valid option values

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Closes #868 
Ensures that the Dropdown component only has a single tab index.
M packages/core/src/components/cv-dropdown/cv-dropdown.vue
=> fix: ensure that CvDropdown has single tabindex for accessibility

packages/core/CHANGELOG.md, packages/core/package.json
- Left and right options added to cv-tooltip
- CvDropdown needed multiple tab presses to move past #868
- CircleCI deployment fix
- Warn on duplicate IDs in table row and tab
- Dependency bot bumps
- Other dependency version bumps
- Update documentation on use of expanded/isExpanded in table rows
=> Release 2-24-0

packages/core/src/components/cv-button/button-mixin.js, packages/core/src/components/cv-button/cv-icon-button.vue
Closes #889
Fix icon-only button tooltip
M       packages/core/src/components/cv-button/button-mixin.js
=> fix: tooltip on icon only button

packages/core/src/components/cv-pagination/cv-pagination-notes.md, packages/core/src/components/cv-pagination/cv-pagination.vue, storybook/stories/cv-pagination-story.js
Closes #893 
Allow user to manually disable forwards and backwards buttons
M       packages/core/src/components/cv-pagination/cv-pagination-notes.md
M       packages/core/src/components/cv-pagination/cv-pagination.vue
M       storybook/stories/cv-pagination-story.js
=> feat: add disabled pagination forwards backwards btn

packages/core/src/components/cv-data-table/_cv-data-table-heading.vue, packages/core/src/components/cv-data-table/cv-data-table-heading-label.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-data-table/index.js, packages/core/src/index.js, storybook/stories/cv-data-table-story.js
Addresses  #890 #758 #891
An experimental effort to allow slotted data table headings but keep style and sort options
R050    packages/core/src/components/cv-data-table/_cv-data-table-heading.vue   packages/core/src/components/cv-data-table/cv-data-table-heading.vue
M       packages/core/src/components/cv-data-table/index.js
M       packages/core/src/index.js
=> Slotted headings

packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue
Closes #903
Adds label text to checkboxes in table.
=> fix: labels in table checkboxes

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-tag/cv-tag.vue
Closes #909 
Ensure interaction with the combo box, dropdown and tag are disabled when the disable properties are set.
M       packages/core/src/components/cv-tag/cv-tag.vue
=> fix: disabled drop combo tag

packages/core/src/components/cv-code-snippet/_cv-code-snippet-inline.vue, packages/core/src/components/cv-code-snippet/_cv-code-snippet-multiline.vue, packages/core/src/components/cv-code-snippet/_cv-code-snippet-oneline.vue, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-feedback-button/_cv-feedback-button.vue, storybook/_storybook/views/sv-template-view/sv-template-view.vue, storybook/stories/cv-data-table-story.js
Closes #914 
- chore: fix aria label on template view
- fix: table skeleton appearance
- fix: dropdown aria warning with no label
- feat: add table oveflow options
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-inline.vue
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-multiline.vue
M       packages/core/src/components/cv-code-snippet/_cv-code-snippet-oneline.vue
R096    packages/core/src/components/cv-code-snippet/_cv-feedback-button.vue …
=> Fix rollup

packages/core/src/components/cv-dropdown/cv-dropdown-notes.md, packages/core/src/components/cv-text-area/cv-text-area-notes.md, packages/core/src/components/cv-text-area/cv-text-area.vue, packages/core/src/components/cv-text-input/cv-text-input-notes.md, packages/core/src/components/cv-text-input/cv-text-input.vue, storybook/stories/cv-dropdown-story.js, storybook/stories/cv-text-area-story.js, storybook/stories/cv-text-input-story.js, storybook/stories/cv-tooltip-story.js
Closes #926 
Adds focus method to cv-text-area and cv-text-input
M       packages/core/src/components/cv-dropdown/cv-dropdown-notes.md
M       packages/core/src/components/cv-text-area/cv-text-area-notes.md
M       packages/core/src/components/cv-text-area/cv-text-area.vue
M       packages/core/src/components/cv-text-input/cv-text-input-notes.md
M       storybook/stories/cv-dropdown-story.js
M       storybook/stories/cv-text-area-story.js
M       storybook/stories/cv-text-input-story.js
M       storybook/stories/cv-tooltip-story.js
=> feat: add focus method to text inputs

packages/core/src/assets/images/example-icon-svg.js, packages/core/src/assets/images/example-icon.svg, packages/core/src/components/cv-button/cv-button-notes.md, packages/core/src/components/cv-button/cv-button.vue, packages/core/src/components/cv-button/cv-icon-button.vue, packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue, packages/core/src/components/cv-content-switcher/cv-content-switcher-notes.md, packages/core/src/components/cv-svg/_cv-svg.vue, storybook/stories/cv-button-story.js
Closes #925 
Expands how icons can be specified for buttons to include an SVG path (without ID does not style) and raw SVG.
A       packages/core/src/assets/images/example-icon-svg.js
A       packages/core/src/assets/images/example-icon.svg
M       packages/core/src/components/cv-button/cv-button-notes.md
M       packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue
M       packages/core/src/components/cv-content-switcher/cv-content-switcher-notes.md
A       packages/core/src/components/cv-svg/_cv-svg.vue
M       storybook/stories/cv-button-story.js
=> fix: improve svg icon support

packages/core/__tests__/__snapshots__/cv-button.test.js.snap, packages/core/__tests__/__snapshots__/cv-tabs.test.js.snap, packages/core/src/components/cv-accordion/cv-accordion-item.vue, packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, packages/core/src/components/cv-tabs/cv-tab.vue, packages/core/src/components/cv-tabs/cv-tabs.vue, packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue, packages/core/src/components/cv-ui-shell/cv-header-global-action.vue, packages/core/src/components/cv-ui-shell/cv-header-menu-button.vue, packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue
Some aria attributes use the true/false/undefined states to translate as true/false/not-applicable. They are therefore not boolean attributes and should emit attr="false"
https://www.w3.org/TR/wai-aria-1.1/#propcharacteristic_value
M       packages/core/__tests__/__snapshots__/cv-button.test.js.snap
M       packages/core/__tests__/__snapshots__/cv-tabs.test.js.snap
M       packages/core/src/components/cv-accordion/cv-accordion-item.vue
M       packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue
M …
=> fix: aria states for bools(hidden, selected and expanded)

packages/core/CHANGELOG.md, packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select-notes.md, packages/core/src/components/cv-multi-select/cv-multi-select.vue
Closes #956 
Removes validator warning
m - packages/core/src/components/cv-combo-box/cv-combo-box.vue
=> fix: multi select use of filter tag

packages/core/CHANGELOG.md, packages/core/src/components/cv-multi-select/cv-multi-select.vue
Closes #954 
Fixes multi-select with same issue to 954. Combobox fixed accidentally in preverious PR.
=> fix: multi select user filter

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue
Closes #678 
Add the empty class which makes available the space reserved for the clear button
M	packages/core/src/components/cv-combo-box/cv-combo-box.vue
M	packages/core/src/components/cv-multi-select/cv-multi-select.vue
=> fix: empty space in combo and multi

packages/core/src/components/cv-data-table/cv-data-table-action.vue
Closes #970
IE 11 SVG class usage
m packages/core/src/components/cv-data-table/cv-data-table-action.vue
=> fix: ie11 svg class usage

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Clears CvDropdown when value set to a non-child value
m packages/core/src/components/cv-dropdown/cv-dropdown.vue
=> fix: dropdown clearing of value

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Chrome, Firefox and Safari deal with buttons differently. Chrome sets focus on click, Firefox and Safari do not. As a result, it is harder to manage the open state of a dropdown using focus alone. This PR switches to using click outside and tab monitoring instead of focusout.
=> fix: firefox dropdown close

packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-notes.md, storybook/stories/cv-data-table-story.js
Closes #1006
Add aria labels for expanded and collapsed states of expanding rows in the data table.
=> feat: add aria label for expanding row button

packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue, packages/core/src/components/cv-data-table/cv-data-table-heading.vue, packages/core/src/components/cv-data-table/cv-data-table-row.vue, packages/core/src/components/cv-date-picker/cv-date-picker.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-overflow-menu/cv-overflow-menu.vue, packages/core/src/components/cv-toggle/cv-toggle-skeleton.vue, packages/core/src/components/cv-tooltip/cv-definition-tooltip.vue, packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue, packages/core/src/components/cv-ui-shell/cv-header-global-action.vue, packages/core/src/components/cv-ui-shell/cv-header-menu-button.vue
Addresses issue raised int #1007
Add ID to the outer element when ID not otherwise used. A potential breaking change for v3 would separate top level ID from inner IDs.
M       packages/core/src/components/cv-content-switcher/cv-content-switcher-button.vue
M       packages/core/src/components/cv-data-table/cv-data-table-heading.vue
M       packages/core/src/components/cv-toggle/cv-toggle-skeleton.vue
M       packages/core/src/components/cv-tooltip/cv-definition-tooltip.vue
M …
=> fix: use of uidMixin without id use

packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/directives/clickout.js
Closes #1004
Add and use Vue directive to detect click outside of cv-dropdown
A       packages/core/src/directives/clickout.js
=> fix: click outside dropdown

packages/core/src/components/cv-combo-box/cv-combo-box.vue, packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue, packages/core/src/components/cv-data-table/cv-data-table-row.vue, packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue, packages/core/src/components/cv-data-table/cv-data-table.vue, packages/core/src/components/cv-date-picker/cv-date-picker.vue, packages/core/src/components/cv-dropdown/cv-dropdown.vue, packages/core/src/components/cv-modal/cv-modal.vue, packages/core/src/components/cv-multi-select/cv-multi-select.vue, packages/core/src/components/cv-number-input/cv-number-input.vue, packages/core/src/components/cv-select/cv-select.vue, packages/core/src/components/cv-text-area/cv-text-area.vue, packages/core/src/components/cv-text-input/cv-text-input.vue, packages/core/src/components/cv-time-picker/cv-time-picker.vue, packages/core/src/components/cv-ui-shell/cv-header.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue, packages/core/src/components/cv-ui-shell/cv-side-nav-menu.vue, storybook/stories/cv-ui-shell-story.js
Closes #1025 #936 
When using the slot syntax slot="name" beofreUpdate is able to identify whether or not a slot exists. However when switching to the new syntax v-slot:name only the default slot appears in this.$slots. This PR moves the check for slot content to the updated lifecycle method which works for both old and newer syntax.
M       packages/core/src/components/cv-data-table/cv-data-table-skeleton.vue
M …
=> fix: slot not updating with v-slot

packages/core/src/components/cv-date-picker/cv-date-picker.vue, packages/core/src/components/cv-date-picker/plugins/appendToPlugin.js, packages/core/src/components/cv-date-picker/plugins/fixEventsPlugin.js, packages/core/src/components/cv-date-picker/plugins/monthSelectPlugin.js, packages/core/src/components/cv-date-picker/plugins/rangePlugin.js
Closes #434
Makes use of carbon flatipickr plugins defined in carbon-components-react.
A       packages/core/src/components/cv-date-picker/plugins/appendToPlugin.js
A       packages/core/src/components/cv-date-picker/plugins/fixEventsPlugin.js
A       packages/core/src/components/cv-date-picker/plugins/monthSelectPlugin.js
A       packages/core/src/components/cv-date-picker/plugins/rangePlugin.js
=> feat: use carbon flatpickr plugins

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Temporary fixes max-height. It may be replaced by a new implementation for #994  
Adds some missing classes from list-box component.
The code was based on carbon-components-react
References:
- https://github.com/carbon-design-system/carbon/blob/c5a64d27cd7bb41eeea9922bc05afe6c5c2059eb/packages/react/src/components/Dropdown/Dropdown.js#L100
- https://github.com/carbon-design-system/carbon/blob/c5a64d27cd7bb41eeea9922bc05afe6c5c2059eb/packages/react/src/components/Dropdown/Dropdown.js#L103
- https://github.com/carbon-design-system/carbon/blob/c5a64d27cd7bb41eeea9922bc05afe6c5c2059eb/packages/react/src/components/ListBox/ListBox.js#L53
```
```
=> fix(cv-dropdown): missing classes

packages/core/__tests__/__snapshots__/cv-search.test.js.snap, packages/core/__tests__/cv-search.test.js
#182
Add tests for CvSearch component. Could not test `@blur` events. Noticed, that some props do not have validators, but should (e.g. `kind`). Also `large` prop value is never actually used (expect one undefined check). Noticed, that some pieces of code are unreachable, i.e. `toggleActive('not boolean')` is never called.
A       packages/core/__tests__/__snapshots__/cv-search.test.js.snap
A       packages/core/__tests__/cv-search.test.js
=> test: add tests for cv-search component

packages/core/src/components/cv-dropdown/cv-dropdown.vue
Closes #1042
Remove unnecessary role="button" on the dropdown chevron.
=> fix: remove down chevron role

packages/core/src/components/cv-combo-box/cv-combo-box-notes.md, packages/core/src/components/cv-data-table/cv-data-table-notes.md, packages/core/src/components/cv-multi-select/cv-multi-select-notes.md, packages/core/src/components/cv-search/cv-search-notes.md, packages/core/src/components/cv-time-picker/cv-time-picker-notes.md, packages/core/src/components/cv-toolbar/cv-toolbar-notes.md, packages/core/src/components/cv-ui-shell/cv-ui-shell-notes.md
Closes #1037
Fix incorrect links into core carbon site.
M       packages/core/src/components/cv-combo-box/cv-combo-box-notes.md
M       packages/core/src/components/cv-multi-select/cv-multi-select-notes.md
M       packages/core/src/components/cv-search/cv-search-notes.md
M       packages/core/src/components/cv-time-picker/cv-time-picker-notes.md
M       packages/core/src/components/cv-toolbar/cv-toolbar-notes.md
M       packages/core/src/components/cv-ui-shell/cv-ui-shell-notes.md
=> fix: notes links to carbondesignsystem.com

packages/core/__tests__/__snapshots__/cv-code-snippet.test.js.snap, packages/core/__tests__/cv-code-snippet.test.js
#182
Add tests for CvCodeSnippet component. Could not test toggleExpand of CvCodeSnippetMultiline partially because I was not able to import it from `@/components/cv-code-snippet`. Noticed that CvCodeSnippetMultiline props `lessText` and `moreText` are actually not reachable from CvCodeSnippet, so they can not be set.
A       packages/core/__tests__/__snapshots__/cv-code-snippet.test.js.snap
A       packages/core/__tests__/cv-code-snippet.test.js
=> test: add tests for cv-code-snippet

packages/core/__tests__/__snapshots__/cv-toolbar.test.js.snap, packages/core/__tests__/cv-toolbar.test.js
#182
Add tests for CvToolbar component. Could not add coverage for @blur event for CvToolbarSearch, even though I tested that the 'active' class is removed on blur.
A       packages/core/__tests__/__snapshots__/cv-toolbar.test.js.snap
A       packages/core/__tests__/cv-toolbar.test.js
=> test: add tests for cv-toolbar

packages/core/__tests__/__snapshots__/cv-tag.test.js.snap, packages/core/src/components/cv-tag/cv-tag.vue
Closes #1032 
Remove tabindex which was no longer needed 
M       packages/core/__tests__/__snapshots__/cv-tag.test.js.snap
M       packages/core/src/components/cv-tag/cv-tag.vue
=> fix: remove extra tabIndex in tag

storybook/stories/cv-combo-box-story.js, storybook/stories/cv-multi-select-story.js
Fixed 2 instances of typos: `hihglight` -> `highlight`.
=> docs: fix some typos

packages/core/src/components/cv-ui-shell/cv-header-panel.vue, packages/core/src/components/cv-ui-shell/cv-side-nav.vue
Closes #1056
Addresses loss of focus prior to click on side panel link in Safari. The UIShell/side panel still has a number of keyboard accessibility issues which should be raised as another issue.
m packages/core/src/components/cv-ui-shell/cv-header-panel.vue 
m packages/core/src/components/cv-ui-shell/cv-side-nav.vue
=> fix: ignore side panel focusout b4 click on safari

packages/core/src/components/cv-modal/cv-modal-notes.md, packages/core/src/components/cv-modal/cv-modal.vue, storybook/stories/cv-modal-story.js
Closes #1068
Adds a new event to `cv-modal` called `after-modal-hidden`, which triggers once the hide transition is finished.
M       packages/core/src/components/cv-modal/cv-modal-notes.md
M       storybook/stories/cv-modal-story.js
=> Add after hidden modal event

packages/core/src/components/cv-modal/cv-modal.vue
Closes #1080 
Currently a `border-bottom` transition can trigger the event early. This fix ensures that the event is only triggered after the modal is no longer visible.
=> fix: ensure no previous transitionend event triggers after-modal-hidden

packages/core/src/components/cv-tooltip/cv-definition-tooltip.vue
As of today, the definition tooltip only accepts `top` and `bottom`. To remain consistent with the `cv-tooltip` definition, I included `left` and `right` options.
Plus, left and right behavior is applied, but the validator function throws an error to the console.
=> Include `left` and `right` to direction validator.

packages/core/src/components/cv-data-table/cv-data-table.vue
Closes #1088
Removes the listeners from the original component definition, and adds the `blur` listeners to the `magnifier` and `search` components in the `mounted` function. At the end, in the `beforeDestroy` function, it removes the listeners to prevent the issue described in #1088 . It also checks if the `searchContainer` component exists, to prevent the same, undefined error happening.
=> fix: cv-data-table listener is called after navigation

packages/core/src/components/cv-tabs/cv-tabs.vue
Closes #1083
This PR changes the `cv-tabs` component, adds the event listeners on `mount` and removes them in `beforeDestroy`, doing this with `this.$refs.tabs` where `tabs` is the root div which previously had the listeners attached as `@focusout="onFocusout" @focusin="onFocusin"`.
=> fix: cv-tabs fails in focusout event when using router-link in a tab

packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue
Contribues to  #1091 
Use the checkSlots pattern in side nav for icons
modified:   packages/core/src/components/cv-ui-shell/cv-side-nav-link.vue
=> fix: use check slot pattern in side nav

packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue, packages/core/src/components/cv-tooltip/cv-tooltip-notes.md, storybook/stories/cv-tooltip-story.js
We had a use case in our app to animate a part of the page when the tooltip is shown and when the tooltip is hidden. There is not an easy way to do this without events emitted from the tooltip so I forked the component to use it in our app.
M       packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue
M       packages/core/src/components/cv-tooltip/cv-tooltip-notes.md
=> feat: add show/hide events to cv-interactive-tooltip

packages/core/src/components/cv-date-picker/cv-date-picker.vue
When swapping out the range plugin for the carbon version left a spurious 'new' which did not show one storybook. Can be seen here with v2.36.0 https://codesandbox.io/s/carbonvue-cvdatepicker-i1lyy?file=/src/App.vue
m. packages/core/src/components/cv-date-picker/cv-date-picker.vue
=> fix: cv-date-picker range plugin  use

packages/v3/src/components/CvButton/CvButton.stories.js, packages/v3/src/global/storybook-utils/__tests__/split-slot-args.spec.js, packages/v3/src/global/storybook-utils/split-slot-args.js
Undoes the use of slotArgs prefix in favour of extracting specific args as slots.
Checked storybook still worked and split-slot-args tests still passed.
=> chore: tidy button story slotArgs

packages/core/src/components/cv-modal/cv-modal-notes.md, packages/core/src/components/cv-modal/cv-modal.vue, storybook/stories/cv-modal-story.js
Contributes to #1165
- Fix modal (accidentally partially merged)
- Adds third button
- Updates documentation and storybook
Updating to carbon 10.30
Checked in storybook
=> fix: modal 10-30 updates

packages/core/__tests__/__snapshots__/cv-text-input.test.js.snap, packages/core/src/components/cv-text-input/cv-text-input.vue
Contributes to `CvTextInput`
I conditionally added classes that are apparently needed for the password visibility toggle
When working with VueCarbonComponents I noticed that the password visibility toggle was missing some styles. When comparing the Vue Component with its corresponding React Component I noticed that those classes were missing although the styles were already included.
I ran the command included in package.json (`yarn test`). I don't know if this is sufficient, but I couldn't find any information on the correct procedure. Updated the Snapshot as well.
=> Bugfix: Add missing Classes to CvTextInput (Password Visibility Toggle)

packages/core/__tests__/__snapshots__/cv-text-input.test.js.snap, packages/core/src/components/cv-text-input/cv-text-input.vue
Contributes to `CvTextInput`
There's a bug when a `CvTextInput` of type `password` has a invalid state. The "show password" button and the invalid indicator overlap eachother:
(I took this screenshot from [https://vue.carbondesignsystem.com/?path=/story/components-cvtextinput--default](https://vue.carbondesignsystem.com/?path=/story/components-cvtextinput--default) today.
I added the missing classes so the buttons don't overlap: 
As you can see, there's still a spacing problem on the last button. This issue will be solved with the changes introduced by PR #1179. Here's a screenshot with both changes incorporated:
I found this bug while working on a project. I managed to fix it on my own, so I took the opportunity to contribute to this project.
After I updated the snapshot files for …
=> Add missing classes for invalid password input

packages/core/src/components/cv-tile/_cv-tile-expandable.vue, packages/core/src/components/cv-tile/cv-tile-notes.md, packages/core/src/components/cv-tile/cv-tile.vue, storybook/stories/cv-tile-story.js
Contributes to #1165 
Updated the expandable tile to match the current Carbon implementation
Checked in storybook
=> feat: update tile to 1030

packages/core/__tests__/__snapshots__/cv-tooltip.test.js.snap, packages/core/src/components/cv-tooltip/cv-interactive-tooltip.vue, packages/core/src/components/cv-tooltip/cv-tooltip-notes.md
Contributes to #1159 
Update the interactive tooltip with alignment.
=> feat: v2 tooltip to 1030

packages/core/src/components/cv-modal/cv-modal.vue
Contributes to #1201 
Remove the outer arrow function to call the click handler upon a button click.
To allow the component to properly emit the primary button click.
N/A
=> Fix `primary` button click event

packages/core/__tests__/cv-file-uploader.test.js, packages/core/src/components/cv-file-uploader/cv-file-uploader.vue
Fix #1223 
- made the accept attr a prop
- checked if dropped files have the same mime type or extensions as the informed in the accept prop
- added special case for jpeg files
because there was a comment there saying it should be implemented and an issue for it.
I inspired my code in the [carbon-react implementation](https://github.com/carbon-design-system/carbon/blob/0dfde60e30a3e1238d49b66950362fd39a2c7ca7/packages/react/src/components/FileUploader/FileUploaderDropContainer.js#L65)
I created unit tests and tested with the local storybook
=> fix(file-uploader): mark files with invalid types/formats

packages/core/__tests__/__snapshots__/cv-inline-notification.test.js.snap, packages/core/__tests__/cv-inline-notification.test.js, packages/core/src/components/cv-inline-notification/cv-inline-notification.vue, storybook/stories/cv-inline-notification-story.js
Closes #1210
- Added **hideCloseButton** prop to the **Inline Notification** component
- Added snapshot tests for the case of this prop being true
- Updated storybook page
- This prop was missing from the component
- There was an open issue about it 
- Checked if the storybook was updated and toggled the property on and off to check if the results were as expected
- Wrote a snapshot test passing the new prop as true
=> feat: adding hideCloseButton prop to cv-inline-notification

packages/core/__tests__/__snapshots__/cv-toast-notification.test.js.snap, packages/core/__tests__/cv-toast-notification.test.js, packages/core/src/components/cv-inline-notification/cv-inline-notification-notes.md, packages/core/src/components/cv-toast-notification/cv-toast-notification-notes.md, packages/core/src/components/cv-toast-notification/cv-toast-notification.vue, storybook/stories/cv-toast-notification-story.js
Add hideCloseButton to toast notification
Missing feature 
Test and storybook
=> feat: add hide close to toast

packages/core/src/components/cv-data-table/cv-data-table.vue
Updated the DOM for the data table search
The search did not expand and was incorrectly formatted.
Yes in Storybook, there is a slight sizing glitch on expand.
=> fix: data search size n expand

packages/core/src/components/cv-tabs/cv-tabs.vue
Closes #1286 #1319 #1255
The A11y issue identified in #1255 has a number of solutions. This adopts or rather completes a previous attempt at the Carbon solution of moving the aria-... attributes down to a button contained in the tab.
To address a11y issue.
Storybook & ran tests.
=> fix: address a11y issue raised in

packages/core/src/carbon.yml
- Updated Carbon Vue library description per design spec: https://airtable.com/shrdwElZNyJdGtZkS/tblE2Y75BfY0Z0T2O/viwiUj1cNATMWrkSy/rechGMBkWisSw0prL
- Indexed the Vue tutorial to be part of the library
So next version of Carbon website can have Carbon Vue content.
Updated library description:
The tutorial pages render:
Step 5 will render when https://github.com/carbon-design-system/carbon-platform/issues/1182 is fixed.
=> docs: index vue tutorial

packages/core/src/carbon.yml
Related: https://github.com/carbon-design-system/carbon-platform/issues/967
The Carbon Vue library has a design kits page, to list compatible design kits with the components/patterns in the Carbon Vue library: https://next.carbondesignsystem.com/libraries/carbon-components-vue/latest/design-kits
This list of `designKits` would normally be inherited from the `carbon-styles` library (PR https://github.com/carbon-design-system/carbon/pull/12033), but Carbon Vue has yet to upgrade to v11.
By not inheriting `designKits`, we can specify in this library so the v10 Figma kits are listed, not the new v11 Figma kits.
Once Carbon Vue updates to v11, we can remove the `designKits` array in the config file.
- Added `designKits` array to the index
- See above
- The YML is valid according to our schema …
=> docs: index compatible design kits

packages/core/src/carbon.yml
As found in https://github.com/carbon-design-system/carbon-platform/issues/907, added a "Get started" page to the Carbon Vue library with https://carbondesignsystem.com/developing/frameworks/vue content.
=> docs: index getting started content

packages/core/src/components/cv-modal/cv-modal.vue
Contributes to #1408 
Added `role="separator"` to the before/after modal divs. Also added required value `aria-valuenow` to both 
Tested locally in Storybook with IBM accessibility checker
=> fix: set aria role separator on modal before/after content

.github/workflows/deploy-vue-storybook.yml
Contributes to https://github.com/carbon-design-system/carbon/issues/12171 and https://github.com/carbon-design-system/carbon-components-vue/issues/1364
Add new steps to the deployment workflow to deploy the storybook to GitHub Pages. The existing IBM Cloud deploy was not modified.
This is the first step towards removing the IBM Cloud deploy due to the upcoming sunset of Cloudfoundry. Instead of publishing the storybook to Carbon's IBM Cloud account, storybooks will be published to github pages.
Once this is merged in, I'll move `vue.carbondesignsystem.com` to point to the github pages deployment, then issue another PR to remove the IBM cloud deploy. This will ensure no downtime on the storybook.
We just did this same update in the main Carbon repo and [it's …
=> ci(storybook): deploy to github pages

.github/workflows/deploy-vue-storybook.yml, storybook/_storybook/views/sv-template-view/sv-versions.vue, storybook/_storybook/views/sv-template-view/sv-welcome.vue
Per slack discussion, deploy both Vue 2 and Vue 3 storybook to the same GitHub pages. 
Vue2 https://vue.carbondesignsystem.com/
Vue3  https://vue.carbondesignsystem.com/vue3/
The Vue2 welcome and version pages changed to point to the new vue3 storybook.
Make both storybooks available in the same location
Deployed it to [my own forked repo](https://davidnixon.github.io/carbon-components-vue/?path=/story/welcome--default)
=> chore: combine Vue2 & Vue3 storybooks in GitHub pages

src/components/CvUIShell/CvSideNavMenu.vue
Basically I set the prop `immediate` to `true` of `expanded` watch
By default, the prop `immediate` is `false` and when we try to set to `true` it's ignored
```vue
<CvSideNavMenu :title="title" :expanded="true">
...
</CvSideNavMenu>
``` 
I forked the repo and make the changes. Then I tested in my app and it worked.
=> fix: set immediate to true of expanded watch prop from side nav menu

src/components/CvLink/CvLink.stories.js, src/components/CvLink/CvLink.vue, src/components/CvLink/__tests__/CvLink.spec.js, src/components/CvLink/index.js, src/use/cvLink.js
Contributes to #1434 
Port CvLink component to vue3, covering the same functionalities at the vue2 implementation and a small update in 'useLinkProps' to also add 'role' attribute when link is disabled.
Edit: I've also left the story more like the react one: a child story for each 'state' instead of how it's in vue2.
Yes. Although, Since most tests assert template changes based on props received, they are not exactly following `@testing-library`'s guidelines on replicating user behavior.
=> feat: CvLink implementation for Vue3

storybook/_storybook/views/sv-template-view/sv-versions.vue, storybook/_storybook/views/sv-template-view/sv-welcome.vue
Changed the links in the vue3 vue2 storybooks to properly point to the vue2/vue3 versions. 
The combined storybook build and deployed worked great. The links:
- vue2 is here https://vue.carbondesignsystem.com/?path=/story/welcome--default
- vue3 is here https://vue.carbondesignsystem.com/vue3/?path=/story/carbon--welcome
However the links in the storkbooks to vue3 are broken. ☹️ 
The current link to vue3 is `https://vue.carbondesignsystem.com/carbon-components-vue/vue3/`
Notice the extra **carbon-components-vue** in the path. This is because when testing with GitHub pages, the repo name is part of the path but when accessed via the custom domain, its not there. 
I added a compute property to calculate the vue2 & vue3 URLs based on if `carbon-components-vue` is in the URL path or not. When …
=> fix: sb vue2 & vue3 paths

.github/workflows/release-vNext.yml
Change title of release workflow for vNext and change typo in `actions/setup-node@v3`
https://github.com/carbon-design-system/carbon-components-vue/actions/runs/4515376724/jobs/7952598848
=> fix: change title and change @3 to @v3

README.md
Contributes to `vNext` README.md file
Update of the README.md file, adding the instructions on how to run the storybook.
Because these instructions can help new contributors test their components.
By watching the README.md file in my fork.
=> fix: update vNext README.md file to include storybook instructions

.storybook/styles.scss, src/components/CvForm/CvForm.stories.mdx, src/components/CvForm/CvForm.vue, src/components/CvForm/CvFormGroup.vue, src/components/CvForm/CvFormItem.vue, src/components/CvForm/__tests__/CvForm.spec.js, src/components/CvForm/__tests__/CvFormGroup.spec.js, src/components/CvForm/__tests__/CvFormItem.spec.js, src/components/CvForm/index.js
Contributes to #1451 
CvForm, CvFormGroup and CvFormItem implementation for vue3, following vue2 implementation and react-carbon v7 as base
Using both unit tests and through the stories
=> feat: implement CvForm, CvFormGroup and CvFormItem

main.js, src/components/CvButton/CvButtonSkeleton.stories.js, src/components/CvDropdown/CvDropdown.vue, src/components/CvRadioButton/CvRadioButton.stories.js, src/components/CvRadioButton/CvRadioButton.vue, src/components/CvRadioButton/CvRadioGroup.vue, src/components/CvRadioButton/__tests__/CvRadioButton.spec.js, src/components/CvRadioButton/__tests__/__snapshots__/CvRadioButton.spec.js.snap, src/components/CvRadioButton/index.js, src/use/index.js, src/use/useMethods.js, src/use/useRadio.js
Contributes to #1482
ported CvRadioButton to Vue3
please see CvRadioButton.spec.js (tests from Vue2 adapted)
=> feat: port CvRadioButton to Vue3

main.js, src/components/CvButton/CvButtonSkeleton.stories.js, src/components/CvTooltip/CvDefinitionTooltip.stories.js, src/components/CvTooltip/CvDefinitionTooltip.vue, src/components/CvTooltip/CvInteractiveTooltip.stories.js, src/components/CvTooltip/CvInteractiveTooltip.vue, src/components/CvTooltip/CvTooltip.stories.js, src/components/CvTooltip/CvTooltip.vue, src/components/CvTooltip/__tests__/CvTooltip.spec.js, src/components/CvTooltip/__tests__/__snapshots__/CvTooltip.spec.js.snap, src/components/CvTooltip/consts.js, src/components/CvTooltip/index.js, src/components/CvTooltip/sbTooltipPrefix.js
Contributes to #1489
ported CvTooltip, CvDefinitionTooltip, CvInteractiveTooltip to Vue3
see src\components\CvTooltip\__tests__\CvTooltip.spec.js
=> feat: port CvTooltip to Vue3

src/components/CvTextArea/CvTextArea.stories.js, src/components/CvTextArea/CvTextAreaSkeleton.stories.js, src/components/CvTextArea/CvTextAreaSkeleton.vue, src/components/CvTextArea/StorybookGroupConst.js, src/components/CvTextArea/__tests__/CvTextAreaSkeleton.spec.js, src/components/CvTextArea/__tests__/__snapshots__/CvTextAreaSkeleton.spec.js.snap, src/components/CvTextArea/index.js
Contributes to #1516
Ported CvTextAreaSkeleton from React to Vue3
added spec.js
=> feat: cv-text-area-skeleton ported from React to Vue3

src/components/CvNotification/CvToastNotification.stories.js, src/components/CvNotification/CvToastNotification.vue, src/components/CvNotification/__tests__/CvToastNotification.spec.js
Contributes to #1514
Added more slots to CvToastNotification
btw. fixed toast notification close button class name
To give more granular control over component content
added test suits to spec.js
=> feat: cv-toast-notification add more slots

src/components/CvOverflowMenu/CvOverflowMenu.stories.mdx, src/components/CvOverflowMenu/CvOverflowMenu.vue, src/components/CvOverflowMenu/CvOverflowMenuItem.vue, src/components/CvOverflowMenu/__tests__/CvOverflowMenu.spec.js, src/components/CvOverflowMenu/index.js
Contributes to #1524
Fixed placement and position for cv-overflow-menu so it will behave as in Vue2 (the menu's dropdown is appended to document.body)
=> fix: overflow menu dropdown placement and position

src/components/CvTag/CvTag.stories.js, src/components/CvTag/CvTag.vue, src/components/CvTag/CvTagSkeleton.stories.js, src/components/CvTag/CvTagSkeleton.vue, src/components/CvTag/__tests__/CvTag.spec.js, src/components/CvTag/__tests__/CvTagSkeleton.spec.js, src/components/CvTag/index.js
Contributes to https://github.com/carbon-design-system/carbon-components-vue/issues/1526
-  Added `small` property to change component size (chosen `small` instead `size` because is the only available option for this component)
- Created end tag for skeleton div, `<div/>` is not the best option
- Reorganized initial tagClasses, we doesn't need to set `kind` classes when skeleton component is being used
- Set label on Skeleton scenario in the Storybook (fixing console warn above)
- Created CvTagSkeleton for migration purposes by having a separated component to use Skeleton (preserving Vue 2 pattern)
- Created unit tests
- Checked Storybook behaviors and it's console
=> feat: CvTag / CvTagSkeleton changes

src/components/CvTabs/CvTabs.stories.mdx, src/components/CvTabs/CvTabs.vue, src/components/CvTabs/__tests__/CvTabs.spec.js, src/components/CvTabs/__tests__/__snapshots__/CvTabs.spec.js.snap
Contributes to #1522
Added slot to customise tab switching buttons' content
added test for slot in CvTabs.spec.js
sample:
=> feat: add slot to gain control over tabs switching buttons

src/components/CvFileUploader/CvFileUploader.stories.mdx, src/components/CvFileUploader/CvFileUploader.vue, src/components/CvFileUploader/__tests__/CvFileUploader.spec.js
Contributes to #1519 
- Define `.jpg, .png` as initial values for `accept` at file uploader storybook
- Define `Add file` as button label at file uploader storybook
- Setup `initialStateUploading` as prop. Although used on code, it was set at the props definition (`defineProps`)
- Fix a bug were state was not correctly set on reuploaded files
- Setup `disabled` prop
- Adjust value emitted on `onItemRemove` to comply with vue3 setup mode
- Fix invalid value emitted exposed method `clear`
- Add tests to exposed methods
- Add missing 'button' kind to `inputKinds` array at spec
#1520 is taking a more than expected due to limitations on storybook controls feature. As a few bugs were found and a missing feature, `disabled`, was created, a separate PR will split some of the responsibility and …
=> fix: cv-fileuploader - doc updates, disabled & initialStateUploading props and bug fixes

.github/ISSUE_TEMPLATE/improve-component.md, .github/workflows/ci.yml, .github/workflows/deploy-vue-storybook.yml, .github/workflows/release-vNext.yml, .github/workflows/release.yml, .storybook/Welcome/sv-welcome.vue, README.md
Prepare to switch vNext to be main branch
- update Vue 3  issue template
- update CI to remove vNext reference
- update story book build to move Vue 3 to main page and Vue 2 to /vue2 page
- update release action to have Vue 2 in the name. (Likely this will not get used but I want to keep it around a while.)
- update vue 3 release action to remove "alpha" and the "next" dist tag. This will make Vue 3 the default install for `npm add @carbon/vue`
- update the vNext README to show this is the main branch
=> feat: switch to vue 3

src/components/CvTextInput/CvTextInput.stories.js, src/components/CvTextInput/CvTextInputSkeleton.vue, src/components/CvTextInput/__tests__/CvTextInput.spec.js, src/components/CvTextInput/index.js
Contributes to #167
Implemented `cv-text-input-skeleton`.
Because Carbon Vue rocks 😄 . And it was requested on #167.
Ran the existing unit tests and added new ones.
(I updated the storybook. Is there anything else that needs to be updated?)
=> feat(cv-text-input-skeleton): add CvTextInputSkeleton

src/components/CvDataTable/CvDataTable.vue
Clicking on a sortable header in a CvDataTable (e.g. the first two columns in [the official story book](https://vue.carbondesignsystem.com/?path=/story/component-cvdatatable--default-story) didn't actually trigger the expected events:
* the sort icon for that column remained 'unsorted'
* the action always has `order: undefined`
The code that emits `cv:sort` when clicking on a `CvDataTableHeading` [uses the key `value`](https://github.com/carbon-design-system/carbon-components-vue/blob/43ed9bdfdb32725966e12da7ae059a39e7ef60c4/src/components/CvDataTable/CvDataTableHeading.vue#L119):
```js
function onSortClick() {
bus?.emit('cv:sort', {
heading: { id: cvId.value, name: props.name },
value: nextOrder[internalOrder.value],
});
}
```
However, the receiving code [destructs `payload` into a …
=> fix: CvDataTable did not properly store/emit sort events

.storybook/manager.js, .storybook/postinstall.js, package.json, src/components/CvFileUploader/CvFileUploader.stories.mdx, src/components/CvFileUploader/CvFileUploaderItem.vue, src/components/CvFileUploader/__tests__/CvFileUploaderItem.spec.js
Contributes to #1519 
- ~~Set '.jpg, .png' as initial values for `accept` prop, so users can check invalid state right away~~ (#1529)
- ~~Update button story label to better translate its state~~ (#1529)
- (WIP) allow user to play with the exposed methods
- Improve user experience / align the current documentation w/ react's
=> docs: cv-file-uploader docs enhancements

src/components/CvLink/CvLink.vue, src/components/CvLink/__tests__/CvLink.accessibility.spec.js
Contributes to #1538 
Add a11y test for `CvLink`
Adding 3 test cases, for simple link, one in disabled state and the other one with an icon
Using testing library, the icon one is failing because needs a label, but I'm not sure how to proceed
I have an idea of naming convention for accessibility tests, maybe we can use the abbreviation, `[Component].a11y.spec.js`?
Thank you in advance
=> test(cv-link): add tests for a11y

src/components/CvComboBox/CvComboBox.vue, src/components/CvDataTable/CvDataTable.vue, src/components/CvDropdown/CvDropdown.stories.mdx, src/components/CvDropdown/CvDropdown.vue, src/components/CvDropdown/CvDropdownItem.vue, src/components/CvDropdown/__tests__/CvDropdown.spec.js, src/components/CvLoading/CvLoading.vue, src/components/CvMultiSelect/CvMultiSelect.stories.mdx, src/components/CvMultiSelect/CvMultiSelect.vue, src/components/CvMultiSelect/__tests__/CvMultiSelect.spec.js, src/components/CvProgress/CvProgressStep.vue, src/components/CvSearch/CvSearch.stories.mdx, src/components/CvSearch/CvSearch.vue, src/components/CvTabs/CvTabs.vue, src/components/CvTabs/__tests__/__snapshots__/CvTabs.spec.js.snap, src/components/CvTooltip/CvInteractiveTooltip.vue
While doing a migration build of one of our apps I found 2 issues.
- Some aria attributes require a strings "true" or "false" but were instead set to boolean true or false. This raised a warning in the vue migration build
- Similarly, the aria-disabled attribute should be true or should be omitted. This raised a warning in the vue migration build.
- https://v3-migration.vuejs.org/breaking-changes/attribute-coercion.html#overview
- I misunderstood the [v-model change in Vue 3](https://v3-migration.vuejs.org/breaking-changes/v-model.html#overview). I corrected that in cv-dropdown, cv-multiselect, and cv-search
=> chore: migration coercion fixes

src/components/CvDatePicker/CvDatePicker.vue, src/components/CvModal/CvModal.vue, src/components/CvModal/__tests__/CvModal.spec.js, src/components/CvModal/index.js, src/components/CvMultiSelect/CvMultiSelect.vue, src/components/CvNotification/CvInlineNotification.stories.js, src/components/CvNotification/CvInlineNotification.vue, src/components/CvNotification/CvInlineNotificationTemplate.mdx, src/components/CvSearch/CvSearch.vue, src/components/CvTabs/CvTabs.vue
- avoid more warning related to attributes using boolean values. Attributes that need "true" or "false" string now use strings. Attributes that are supposed to be removed if the boolean is false now use "boolean || null"
- add constants for modal kinds and size. This fits  with strategy in #591 
- issue console warning for validation failure in modal
- watching an array require "deep" to be set to true
- The inline notification subtitle supports html in Vue 2 but not Vue 3. Add a slot for user (like me) who need this feature. Also added slot for `title`. Also add doc for the slots to the storybook.
Compiling another app with vue migration/compatibility mode revealed these issues
=> fix: fixes related to migration/compat build

src/components/CvCheckbox/CvCheckbox.vue, src/components/CvCheckbox/__tests__/CvCheckbox.accessibility.spec.js, src/components/CvCheckbox/__tests__/CvCheckbox.spec.js, src/components/CvList/__tests__/CvList.accessibility.spec.js, src/components/CvRadioButton/CvRadioButton.stories.js, src/components/CvRadioButton/CvRadioButton.vue, src/components/CvRadioButton/CvRadioGroup.vue, src/components/CvRadioButton/__tests__/CvRadioButton.accessibility.spec.js, src/components/CvRadioButton/__tests__/CvRadioButton.spec.js, src/components/CvRadioButton/__tests__/__snapshots__/CvRadioButton.spec.js.snap
Contributes to #1538 
Add CvList, CvCheckbox, CvRadioButton, CvRadioGroup accessibility tests and fix components and tests if needed.
To make component more accessible.
With the `expect(...).toBeAccessible(...)` built in utility.
This component did not have a `fieldset`, `legend` pair, my solution was based on the [v10 react component](https://github.com/carbon-design-system/carbon/blob/v10/packages/react/src/components/RadioButtonGroup/RadioButtonGroup.js#L177).
The tamplate changed from this:
To this:
=> fix: a11y tests for CvList, CvCheckbox, CvRadioButton, CvRadioGroup

src/components/CvDatePicker/CvDatePicker.stories.js, src/components/CvDatePicker/CvDatePicker.vue
Contributes to #1574
Resolve question from slack
> Developer tools in Google Chrome has an error when deleting the value of the CvDatePicker(kind = single) in the Backspace Key. (I'm using Windows, I haven't tried Mac)
In this case, property bind v-model of CvDatePicker it will not be cleared for property, but appearance will be cleared.
And the I think CvDatePicker Stroybook having the same problem. (similar errors will be displayed in the developer tools)
Storybook : https://vue.carbondesignsystem.com/?path=/story/component-cvdatepicker--single-using-date
Add a v-model to the "single-using-date" story to facilitate testing
=> fix: date picker input backspace

src/components/CvBreadcrumb/CvBreadcrumb.vue, src/components/CvBreadcrumb/CvBreadcrumbItem.vue, src/components/CvButton/CvButton.vue, src/components/CvButton/CvButtonSet.vue, src/components/CvButton/CvIconButton.vue, src/components/CvCodeSnippet/CvCodeSnippet.vue, src/components/CvCodeSnippet/_CviCodeSnippetInline.vue, src/components/CvCodeSnippet/_CviCodeSnippetMultiline.vue, src/components/CvCodeSnippet/_CviCodeSnippetOneline.vue, src/components/CvCodeSnippet/__tests__/CvCodeSnippetSkeleton.spec.js, src/components/CvComboBox/CvComboBox.vue, src/components/CvList/CvList.vue, src/components/CvList/CvListItem.vue, src/components/CvList/__tests__/CvList.spec.js, src/components/CvNotification/CvInlineNotification.vue, src/components/CvNotification/CvToastNotification.vue, src/components/CvNotification/__tests__/CvInlineNotification.spec.js, src/components/CvNotification/__tests__/CvToastNotification.spec.js, src/components/CvTag/CvTag.vue
Contributes to #1581
Replicated missing `cv-` classes that were present on the components in Vue2
To minimise amount of changes we need to do when migrating to Vue3
run updated tests
=> fix: replicate missing `cv-` classes from Vue2 repo

.storybook/theme.js
Updated storybook brandUrl.
It still pointed to `packages/v3`, but `v3` is in `root` now.
Build storybook locally, and clicked the brand name
=> fix(storybook): brandUrl point to main root

src/components/CvDatePicker/CvDatePicker.stories.js, src/components/CvDatePicker/CvDatePicker.vue
Contributes to issue from slack
Tweaked the date picker to make `calOptions` reactive.
Add reactive options to storybook and tested in separate app.
=> fix: add calOptions as reactive prop

src/components/CvTag/CvTag.stories.js, src/components/CvTag/CvTag.vue
Contributes to #1588
Restored CvTag default color used in Vue2 
To preserve consistency for when migrating from Vue2 to Vue3. Also red is not the color that is the best as default value (is not neutral)
Run unit tests; visually on served Storybook
=> fix: restore CvTag default color from Vue2

src/components/CvCheckbox/CvCheckbox.vue
Contributes to #1594
Fix: unfocus checkbox style on blur
Te code was broken
Visually, run unit tests for CvCheckbox
=> fix: unfocus CvCheckbox (add missing 'value' access to ref)

.storybook/postinstall.js, devPreinstall.js, package.json
Contributes to #1576
Possible fix for npm 20+ install issues.
- renamed prepare.js to devPreinstall.js to better account for how it is used. (Name inspired pnpm lifecycle script.)
- Do not throw error in devPreinstall.js. Instead, issue warning.
- Try catch operations in .storybook/postinstall.js & log successful completion
- Add "node" in front of "ibmtelemetry". This should not be needed since node_modules/.bin/ibmtelemetry includes "#!/usr/bin/env node". But experimentally, this is required at least by npm 20+
See "this fails" steps in #1576 
[carbon-vue-3.0.15-4a6cf.tgz](https://github.com/user-attachments/files/15538791/carbon-vue-3.0.15-4a6cf.tgz)
```sh
nvm use 20 # - Now using node v20.13.1 (npm v10.5.2)
npm create vite@latest app-name -- --template vue
cd add-name
npm install
Run …
```
=> fix: npm 20+ install

src/components/CvComboBox/CvComboBox.vue
Contributes to #1604
Fixed code, where access to Proxy was missing a 'value'
=> fix: CvComboBox arrows navigation failing due to missing value access to Proxy

package.json, src/components/CvGrid/index.js
This PR fixes #1608.
I just added the CvGrid's index.js that was missing. It was not possibile to import and use CvGrid and its components otherwise.
=> fix: created index.js for cv-grid and related components

package.json, packrat.js
Contributes to #1576 
1. Move the local development postinstall (hooks for husky etc) out of the scripts area of package.json during packaging
2. Copy the package / prod postinstall (ibm telemetry) from "packrat" area of package.json to "scripts" during packaging
Since the dev postinstall is no longer in scripts there is no way for npm to find and run it. Right?
I think npm 10 may be running everything with a "_postinstall" suffix so another alternative would be to rename the "dev_postinstall"  to something else. Moving completely out of scripts area seems safer.
[carbon-vue-3.0.17-8eb61.tgz](https://github.com/user-attachments/files/16174354/carbon-vue-3.0.17-8eb61.tgz)
node 20/npm 10 issues
locally with local package tgz package
=> build: move dev postinstall

src/components/CvFileUploader/CvFileUploader.vue
Contributes to #1607 
Updated to current File object coming from event to internalFile so that if a file has been modified the internalFiles are updated
I have case where the user may add a .docx file with the same name but modified, and the current component is not updating with the modified file.
With local test environment
=> feat: cv-file-uploader update to current File object coming from event to internalFile

.storybook/manager-head.html
Adding mandatory intrumentation tags for Carbon Vue storybook
Per IBM OPRT audit, we are required to have proper instrumentation on all domains owned by IBM. This will bring the Carbon Vue storybook into compliance.
=> chore(ibm-common): adding mandatory intrumentation tags

src/components/CvTag/CvTag.stories.js, src/components/CvTag/CvTag.vue
Add icons to match support in React.
https://react.carbondesignsystem.com/?path=/docs/components-tag--overview
added optional new prop `renderIcon` to match react.
New requirement for one of my projects.
Local storybook
=> feat: add support for tag icons

src/components/CvDropdown/CvDropdown.vue
Correct accessibility issue with dropdown menu.
Invalid text and warning text were not being announced in screen reader.
Found during development by Alessio Mantegna. Fix also provided by Alessio.
With screen reader in Safari.
Easiest place to test is with the slots story
http://localhost:6006/?path=/story/component-cvdropdown--slots
There you can toggle the warning and invalid slots and confirm they are announced.
=> fix: dropdown menu fix for accessability announcement

.github/workflows/release-v3.yml, addNamedComponentExports.js, src/index.js
Contributes to #1553 
- add `npm publish --provenance` per description in 1553
- add-components-exports is meant run on every publish but was blocked a bit by lerna. Now it will be run.
- Tested locally as best I can but unfortunately due to the nature of  `npm publish --provenance`, I need to merge this and do final testing live. 
- I read a lot of docs about the provenance update and I am able to use this in dry-run mode locally.
=> chore: enable provenance statements and export updates

src/components/CvDatePicker/CvDatePicker.stories.js, src/components/CvDatePicker/CvDatePicker.vue
Contributes to #1625 
- some minor eslint-style changes to the story to put `@` items at the end of the attribute list i.e. `@change="onChange"`
- some minor tidying of controls on stories
- add new emit for `dateChange` this event mimics the `change` event in the Carbon React
- separate the v-model stories for a `single` kind and `range` kind. The v-model is different for each of these and I think separating the stories makes it a bit clearer.
- for `single` kind and `range` kind stories, show the `dateChange` in the actions tab
See #1625 but basically there was no way to listen for changes for a range style date picker.
Via the storybook
=> fix: emit date change event to match React

src/components/CvCheckbox/CvCheckbox.stories.js, src/components/CvDataTable/CvDataTable.stories.mdx, src/components/CvDataTable/CvDataTable.vue, src/components/CvDataTable/CvDataTableRow.vue
Contributes to #1615 
Prevent batch actions from showing for empty tables
Batch actions should not show for empty tables. This is a regression from 3.0.14 as noted in #1615 
Implemented the table search function in the story book. Also tested in hello carbon vue app.
=> fix: data table batch actions

.storybook/preview.js
Noticed the default story is accordion instead of welcome
sort order throw off by recet fix
=> fix: set default story to Welcome

src/components/CvMultiSelect/CvMultiSelect.vue
Contributes to #1648
It adds the title attribute to div to allow user to read all content from a label that exceeds the component width size
I have a case with a list of options that the label is exceeding the width so the user can't read all the content
With local test environment
=> feat: cv-multi-select add title attribute to options

src/components/CvDatePicker/CvDatePicker.vue
Contributes to issue reported via slack
Protect the date picker calOptions watcher 
Looks like from the stack there might be a timing issue where the calendar is still null but the calOptions is updated.
Code inspection
=> fix: protect watcher against null calendar

src/components/CvNumberInput/CvNumberInput.stories.js, src/components/CvNumberInput/CvNumberInput.vue, src/components/CvNumberInput/const.js, src/components/CvTextInput/CvTextInput.stories.js, src/components/CvTextInput/CvTextInput.vue, src/components/CvTextInput/const.js
Contributes to #1669
Add the size property for these inputs  to match react version
These were missing
=> feat: add size property to text and number input 

src/components/CvFileUploader/CvFileUploader.stories.mdx, src/components/CvFileUploader/CvFileUploader.vue, src/components/CvFileUploader/__tests__/CvFileUploader.spec.js
Contributes to #1663 
Update 'drop' event handler, at CvFileUploader, to handle files considering 'multiple' attribute
Fix the drop behavior when multiple is falsy
Yes. Automated tests also added.
=> fix: adjust CvFileUploader drop handler to not ignore 'multiple' attribute

src/components/CvNumberInput/CvNumberInput.vue
Contributes to #1710 
prevent non-numeric input on firefox and Safari
Match React component where similar issue does not exist.
Storybook in FF and Safari
=> fix: prevent non-numeric input on firefox and Safari

src/components/CvDataTable/index.js
Contributes to #1714 
Just exported the CvDataTable related named components
Changing the index.js file in node_modules after install.
=> fix: cv-data-table related named components export

src/components/CvUIShell/CvHeader.vue, src/components/CvUIShell/__tests__/CvHeader.spec.js, src/components/CvUIShell/__tests__/PanelFocusTestComponent.vue
Contributes to #1732 
fix crash when focusing out of right panels
when focusing out of right panels, the emitted event contains a ref to the panel, but the access was not using '.value' to get the actual DOM element, crashing the rest of the logic that relied on it
tests were also added to cover the focus processing.
Bug fixing
1. Followed the same steps as in the issue (testing on storybook)
2. Added unit tests that reproduced the issue and now detects they are fixed
=> fix(cv-header): fix crash when focusing out of right panels
